### ISSUE TITLE
is the java api client backwards compatible with elasticsearch 6.8?

### ISSUE THREAD

**Issue by andykais** [elastic/elasticsearch-java#103]
we are running ES 6.8 in production, but want to take advantage of the new java api client (7.16.2) in a new service. Does this library do anything in the way of backwards compatibility? E.g. detecting the server version? The only thing this service needs to do is use the `index` api, which I know does have breaking changes with mapping types being removed

**Comment by swallez** [comment]
Unfortunately the answer is definitely no. Our [compatibility guidelines](https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/current/introduction.html#_compatibility) only guarantee forward compability with later minor versions of the server.

It _may_ work with earlier versions (with no guarantees made), but in the case of the new Java API client, some additional forward-compatibility features rely on changes that were introduced in Elasticsearch 7.14, and it will therefore definitely not work with prior versions.

**Comment by andykais** [comment]
ok. Thanks for the info
