### ISSUE TITLE
New Java client does not have all fields for CreateApiKeyRequest.RoleDescriptor

### ISSUE THREAD

**Issue by synox** [elastic/elasticsearch-java#106]
**Elasticsearch version** (`bin/elasticsearch --version`):
7.16.2

**Plugins installed**: []

**JVM version** (`java -version`):
openjdk 17

**OS version** (`uname -a` if on a Unix-like system):
not relevant

**Description of the problem including expected versus actual behavior**:
The description in https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-put-role.html mentions fields like `indices`, `global` and `run_as` which are [not defined in the Java client](https://github.com/elastic/elasticsearch-java/blob/main/java-client/src/main/java/co/elastic/clients/elasticsearch/security/create_api_key/RoleDescriptor.java#L53-L57)

They are also not defined in the [service specification](https://github.com/elastic/elasticsearch-specification/blob/main/specification/security/create_api_key/types.ts#L27-L29). 

However, the are defined in the [elasticsearch-rest-high-level-client](https://github.com/elastic/elasticsearch/blob/master/client/rest-high-level/src/main/java/org/elasticsearch/client/security/user/privileges/Role.java#L94-L100). 

I am using the wrong Java API to create an api key? Or should the spec and/or docs be updated?

**Steps to reproduce**:
-

**Provide logs (if relevant)**:

**Comment by swallez** [comment]
The API specification is actually wrong, and these are the same structure. Elasticsearch accepts both `index` and `indices`, which led to this confusion.

https://github.com/elastic/elasticsearch-specification/issues/1555 has been opened to solve this, and the Java client will be updated once it's fixed.

**Comment by swallez** [comment]
This has been fixed in PR #292, backported to version 8.2 in PR #293 and to version 7.17 in PR #294.
