### ISSUE TITLE
How to create index with "index.mapping.ignore_malformed" setting

### ISSUE THREAD

**Issue by jerryguowei** [elastic/elasticsearch-java#112]
I try to use `client.indices().create(r -> r.settings(s -> s.....))`.

but I don't find any variables used for this parameter in the class [IndexSettings](https://github.com/elastic/elasticsearch-java/blob/main/java-client/src/main/java/co/elastic/clients/elasticsearch/indices/IndexSettings.java).
Any ideas?

**Comment by jdrossl** [comment]
I have the same issue, I also posted a question in the forum
https://discuss.elastic.co/t/missing-index-setting-in-the-new-java-client/294739

**Comment by swallez** [comment]
Thanks @jerryguowei, this is indeed the right place to report issues. Full coverage of index settings not complete yet in the [API specification](https://github.com/elastic/elasticsearch-specification/blob/main/specification/indices/_types/IndexSettings.ts) but we're actively working on it.

**Comment by swallez** [comment]
@jerryguowei unless I'm missing something, the `ignore_malformed` setting is defined on each property and not globally at the index level, as in the following example:

```java
client.indices().create(c -> c
    .index(index)
    .mappings(m -> m
        .properties("count", p -> p.integer(i -> i
            .ignoreMalformed(true))
        )
    )
);
```

**Comment by swallez** [comment]
@jdrossl it's not clear in your forum post if this is about cluster settings or index settings. Can you post an example of what you're doing with the HLRC? Thanks.

**Comment by jdrossl** [comment]
hi @swallez , it is about index settings, I use the HLRC to create indexes with custom settings like changing the default analyzer and mapping limits for example `index.mapping.depth.limit`.
Thanks!

**Comment by jerryguowei** [comment]
> @jerryguowei unless I'm missing something, the `ignore_malformed` setting is defined on each property and not globally at the index level, as in the following example:
> 
> ```java
> client.indices().create(c -> c
>     .index(index)
>     .mappings(m -> m
>         .properties("count", p -> p.integer(i -> i
>             .ignoreMalformed(true))
>         )
>     )
> );
> ```

@swallez it can be set globally.  https://www.elastic.co/guide/en/elasticsearch/reference/current/ignore-malformed.html#ignore-malformed-setting
we use HLRC to create indexes with the settings at global level.

**Comment by swallez** [comment]
@jerryguowei this is indeed an issue in the API specification used to produce the Java code.

https://github.com/elastic/elasticsearch-specification/issues/1566 has been opened to solve this, and the Java client will be updated once it's fixed.

@jdrossl the settings you mention [were recently added to the API specification](https://github.com/elastic/elasticsearch-specification/pull/1500) and will be included in the next release of the Java client.

**Comment by swallez** [comment]
https://github.com/elastic/elasticsearch-specification/issues/1566 had been fixed and the Java client code updated, this will be part of the next 8.2 and 7.17 patch releases.
