### ISSUE TITLE
FieldSuggester Builder seems not available

### ISSUE THREAD

**Issue by javapatterns** [elastic/elasticsearch-java#119]
FieldSuggester Builder each method return ObjectBuilder<FieldSuggester> , which should be Builder itselt for next build step. 

Demo codes as below,  .completion will cause error,   due to 'prefix' method returned ObjectBuilder instead of Builder itself. :

FieldSuggester fieldSuggester= FieldSuggester.of(a->a.prefix("").completion(...))

**Comment by swallez** [comment]
This is on purpose, and a pattern used for all union types that represent values that have many variants.

A field suggester can be _either_ a prefix suggester _or_ a completion suggester (or any of its other variants), but not both. So being able to write `a->a.prefix("").completion(...)` would replace the value set with `prefix()` with the one set with `completion()`, which is certainly a bug.

So the result of `a.prefix` is an `ObjectBuilder<FieldSuggester>` that only allows to `build()` the object and forbids choosing another variant.

Hope this helps. We will also expand the docs to better explain this Java pattern.
