### ISSUE TITLE
Not able to build custom Query (QueryVariant)

### ISSUE THREAD

**Issue by jerryguowei** [elastic/elasticsearch-java#121]
I tried to build a custom Query, but the Query.Kind prevent me from doing this.
The reason I want to build a custom query is we have custom Plugins to support the query.
But it looks the new Java client have less support for this.
I just wondering why we use enum here to build Query.Kind, which is really less extensible.

```
public class CustomWildcardQuery extends QueryBase implements QueryVariant
{
@Override
    public Query.Kind _queryKind()
    {
        return Query.Kind...
    }
}
```

**Comment by swallez** [comment]
Thanks for the feedback @jerryguowei. Indeed there is currently no support for custom queries. It will be added in a future revision.

**Comment by swallez** [comment]
We've started work on this in https://github.com/elastic/elasticsearch-java/issues/252

Closing this issue, please subscribe to the above one. Your feedback is of course welcome.
