### ISSUE TITLE
Do we really need FieldValue in request？

### ISSUE THREAD

**Issue by Dyqer** [elastic/elasticsearch-java#122]
```
transport.search(request -> request
                            .index(indexName)
                            .query(query -> query
                                    .term(term -> term
                                            .field("testCaseId")
                                            .value(v -> v.stringValue(realValue)))), Void.class);
```

In HLRC, the type of value is Object, we write less code if omit the FieldValue Builder

**Comment by swallez** [comment]
We want to provide strongly typed values in this client. Fields of type `FieldValue` will have additional overloaded setters for its variants in a future release.

**Comment by l-trotta** [comment]
Closing this as it was fixed in more recent versions of the client, thank you for reporting this!
