### ISSUE TITLE
Serialize DynamicMapping values as booleans instead of string

### ISSUE THREAD

**Issue by henricm** [elastic/elasticsearch-java#139]
Seems like Kibana has problems displaying index templates created with dynamic mappings set to `DynamicMapping.False`. Please see issue:
https://github.com/elastic/kibana/issues/123809

I guess Kibana should be able to handle this, but also, maybe `DynamicMapping` generate boolean values instead of string values?

**Comment by swallez** [comment]
Another manifestation of the same issue, but when `dynamic: true` is returned when getting the index template https://discuss.elastic.co/t/java-unexpected-json-event-value-true-instead-of-key-name-value-string/295740
