### ISSUE TITLE
`RemoteSource` requires optional parameters to be set.

### ISSUE THREAD

**Issue by sothawo** [elastic/elasticsearch-java#152]
When building a reindex request and setting up a `co.elastic.clients.elasticsearch.core.reindex.RemoteSource`, the client code requires me so set the values for `username`, `password`,  `connectTimeout` and `socketTimeout`, they cannot be null.

This contradicts the description of the reindex request at https://www.elastic.co/guide/en/elasticsearch/reference/7.17/docs-reindex.html#reindex-from-remote where it's stated that the username and password are optional, and for the timeout values gives default values when they are not set.

So I think these values should be nullable when building the request (the timeout values are not the problem, I can provide the defaults there).

**Comment by swallez** [comment]
This has been fixed in PR #292, backported to version 8.2 in PR #293 and to version 7.17 in PR #294.
