### ISSUE TITLE
Analysis API with explain fails to parse "attributes" from plugin-installed analyzer

### ISSUE THREAD

**Issue by SunnyBo0302** [elastic/elasticsearch-java#154]
With [nori_analyzer](https://www.elastic.co/guide/en/elasticsearch/plugins/current/analysis-nori-analyzer.html),

request
```
GET _analyze
{
    "analyzer": "nori",
    "text": "abc",
    "explain": true
}
```

response
```
{
    "detail": {
        "custom_analyzer": false,
        "analyzer": {
            "name": null,
            "tokens": [
                {
                    "token": "abc",
                    "start_offset": 0,
                    "end_offset": 3,
                    "type": "word",
                    "position": 0,
                    "bytes": "[61 62 63]",
                    "leftPOS": "SL(Foreign language)",
                    "morphemes": null,
                    "posType": "MORPHEME",
                    "positionLength": 1,
                    "reading": null,
                    "rightPOS": "SL(Foreign language)",
                    "termFrequency": 1
                }
            ]
        }
    }
}
```

Using [analyze API](https://github.com/elastic/elasticsearch-java/blob/17882a489c0d764844affa55855870d4d1d38122/java-client/src/main/java/co/elastic/clients/elasticsearch/indices/ElasticsearchIndicesAsyncClient.java#L104) provided in ElasticsearchIndicesAsyncClient.java

request
```
AnalyzeRequest analyzeRequest = new AnalyzeRequest.Builder()
          .analyzer("nori")
          .text("abc")
          .index(MY_INDEX)
          .explain(true)
          .build();
```

Since there is no such variable "attributes" in [ExplainAnalyzeToken.java](https://github.com/elastic/elasticsearch-java/blob/main/java-client/src/main/java/co/elastic/clients/elasticsearch/indices/analyze/ExplainAnalyzeToken.java) which was present in [RHLC AnalyzeResponse.java](https://github.com/elastic/elasticsearch/blob/7b952c28ff505f6121b027b66844a6d1b27b91c8/client/rest-high-level/src/main/java/org/elasticsearch/client/indices/AnalyzeResponse.java#L36),
there is no way to retrieve response values `"posType", "rightPOS" ,... and etc`.

**Comment by swallez** [comment]
This has been fixed in PR #292, backported to version 8.2 in PR #293 and to version 7.17 in PR #294.
