### ISSUE TITLE
SingleMetricAggregateBase#value should be nullable like valueAsString

### ISSUE THREAD

**Issue by MT-Jacobs** [elastic/elasticsearch-java#155]
`SingleMetricAggregateBase#value` is documented as such -

``` java
	/**
	 * Required - The metric value. A missing value generally means that there was
	 * no data to aggregate, unless specified otherwise.
	 * <p>
	 * API name: {@code value}
	 * <p>
	 * Defaults to {@code 0} if parsed from a JSON {@code null} value.
	 */
	public final double value() {
		return this.value;
	}
```

It's great that this behavior is documented, but the fact we convert, say, an average aggregation to 0 rather than null can be particularly misleading. If the document count is 0, I'd _expect_ the average value to be null since it's impossible to calculate.

Here's one workaround that relies on a bucket's `docCount` (using Kotlin) -

``` kotlin
fun MultiBucketBase.nullableAvg(name: String): Double? = when (this.docCount())
{
    0L -> null
    else -> this.aggregations()[name]?.avg()?.value()
}
```

but I'd much rather have a direct way to pull the nullable value. I'm aware this means that `SingleMetricAggregateBase` would (as one solution) need a boxed primitive rather than the unboxed `double`, but it makes it that much harder for a dev to send an "average" of zero out erroneously.

**Comment by MT-Jacobs** [comment]
For the time being I'm writing an extension function -

``` kotlin
fun SingleMetricAggregateBase.nullableValue(): Double? = when (this.valueAsString()) {
    null -> null
    else -> this.value()
}
```

**Comment by MT-Jacobs** [comment]
Okay, here's one workaround that works for my specific use case - using the doc count in my `when` block -
``` kotlin
fun MultiBucketBase.nullableAvg(name: String): Double? = when (this.docCount())
{
    0L -> null
    else -> this.aggregations()[name]?.avg()?.value()
}
```

**Comment by swallez** [comment]
@MT-Jacobs we used this approach to avoid boxing numbers (there may be a large number of values in aggregation results). And as you found out, the document count allows knowing if the value "real one" of a default value.

I'm therefore closing this issue.
