### ISSUE TITLE
 Provider org.glassfish.json.JsonProviderImpl could not be instantiated: java.lang.ClassCastException: org.glassfish.json.JsonProviderImpl cannot be cast to jakarta.json.spi.JsonProvider

### ISSUE THREAD

**Issue by hyjlmj** [elastic/elasticsearch-java#157]
i use in Kettle 

2022/02/11 20:19:43 - Elasticsearch bulk insert.0 - ERROR (version 9.2.0.0-290, build 9.2.0.0-290 from 2021-06-02 06.36.08 by buildguy) : Unexpected error
2022/02/11 20:19:43 - Elasticsearch bulk insert.0 - ERROR (version 9.2.0.0-290, build 9.2.0.0-290 from 2021-06-02 06.36.08 by buildguy) : org.pentaho.di.core.exception.KettleStepException: 
2022/02/11 20:19:43 - Elasticsearch bulk insert.0 - Error while processing:Provider org.glassfish.json.JsonProviderImpl could not be instantiated: java.lang.ClassCastException: org.glassfish.json.JsonProviderImpl cannot be cast to jakarta.json.spi.JsonProvider
2022/02/11 20:19:43 - Elasticsearch bulk insert.0 - Provider org.glassfish.json.JsonProviderImpl could not be instantiated: java.lang.ClassCastException: org.glassfish.json.JsonProviderImpl cannot be cast to jakarta.json.spi.JsonProvider
2022/02/11 20:19:43 - Elasticsearch bulk insert.0 - 
2022/02/11 20:19:43 - Elasticsearch bulk insert.0 - 	at org.pentaho.di.trans.steps.elasticsearchbulk.ElasticSearchBulk.indexRow(ElasticSearchBulk.java:222)
2022/02/11 20:19:43 - Elasticsearch bulk insert.0 - 	at org.pentaho.di.trans.steps.elasticsearchbulk.ElasticSearchBulk.processRow(ElasticSearchBulk.java:127)
2022/02/11 20:19:43 - Elasticsearch bulk insert.0 - 	at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
2022/02/11 20:19:43 - Elasticsearch bulk insert.0 - 	at java.lang.Thread.run(Thread.java:748)
2022/02/11 20:19:43 - Elasticsearch bulk insert.0 - Caused by: jakarta.json.JsonException: Provider org.glassfish.json.JsonProviderImpl could not be instantiated: java.lang.ClassCastException: org.glassfish.json.JsonProviderImpl cannot be cast to jakarta.json.spi.JsonProvider
2022/02/11 20:19:43 - Elasticsearch bulk insert.0 - 	at jakarta.json.spi.JsonProvider.provider(JsonProvider.java:78)
2022/02/11 20:19:43 - Elasticsearch bulk insert.0 - 	at co.elastic.clients.json.jackson.JsonValueParser.<init>(JsonValueParser.java:39)
2022/02/11 20:19:43 - Elasticsearch bulk insert.0 - 	at co.elastic.clients.json.jackson.JacksonJsonpParser.getValue(JacksonJsonpParser.java:233)
2022/02/11 20:19:43 - Elasticsearch bulk insert.0 - 	at co.elastic.clients.json.JsonpDeserializerBase$8.deserialize(JsonpDeserializerBase.java:255)
2022/02/11 20:19:43 - Elasticsearch bulk insert.0 - 	at co.elastic.clients.json.JsonpDeserializerBase$8.deserialize(JsonpDeserializerBase.java:249)
2022/02/11 20:19:43 - Elasticsearch bulk insert.0 - 	at co.elastic.clients.json.JsonpDeserializer.deserialize(JsonpDeserializer.java:75)
2022/02/11 20:19:43 - Elasticsearch bulk insert.0 - 	at co.elastic.clients.json.ObjectDeserializer$FieldObjectDeserializer.deserialize(ObjectDeserializer.java:72)
2022/02/11 20:19:43 - Elasticsearch bulk insert.0 - 	at co.elastic.clients.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:176)
2022/02/11 20:19:43 - Elasticsearch bulk insert.0 - 	at co.elastic.clients.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:137)
2022/02/11 20:19:43 - Elasticsearch bulk insert.0 - 	at co.elastic.clients.json.JsonpDeserializer.deserialize(JsonpDeserializer.java:75)
2022/02/11 20:19:43 - Elasticsearch bulk insert.0 - 	at co.elastic.clients.json.ObjectBuilderDeserializer.deserialize(ObjectBuilderDeserializer.java:79)
2022/02/11 20:19:43 - Elasticsearch bulk insert.0 - 	at co.elastic.clients.json.DelegatingDeserializer$SameType.deserialize(DelegatingDeserializer.java:43)
2022/02/11 20:19:43 - Elasticsearch bulk insert.0 - 	at co.elastic.clients.json.ObjectDeserializer$FieldObjectDeserializer.deserialize(ObjectDeserializer.java:72)
2022/02/11 20:19:43 - Elasticsearch bulk insert.0 - 	at co.elastic.clients.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:176)
2022/02/11 20:19:43 - Elasticsearch bulk insert.0 - 	at co.elastic.clients.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:137)
2022/02/11 20:19:43 - Elasticsearch bulk insert.0 - 	at co.elastic.clients.json.ObjectBuilderDeserializer.deserialize(ObjectBuilderDeserializer.java:85)
2022/02/11 20:19:43 - Elasticsearch bulk insert.0 - 	at co.elastic.clients.json.DelegatingDeserializer$SameType.deserialize(DelegatingDeserializer.java:48)
2022/02/11 20:19:43 - Elasticsearch bulk insert.0 - 	at co.elastic.clients.json.JsonpDeserializerBase$ArrayDeserializer.deserialize(JsonpDeserializerBase.java:320)
2022/02/11 20:19:43 - Elasticsearch bulk insert.0 - 	at co.elastic.clients.json.JsonpDeserializerBase$ArrayDeserializer.deserialize(JsonpDeserializerBase.java:285)
2022/02/11 20:19:43 - Elasticsearch bulk insert.0 - 	at co.elastic.clients.json.JsonpDeserializer.deserialize(JsonpDeserializer.java:75)
2022/02/11 20:19:43 - Elasticsearch bulk insert.0 - 	at co.elastic.clients.json.ObjectDeserializer$FieldObjectDeserializer.deserialize(ObjectDeserializer.java:72)
2022/02/11 20:19:43 - Elasticsearch bulk insert.0 - 	at co.elastic.clients.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:176)
2022/02/11 20:19:43 - Elasticsearch bulk insert.0 - 	at co.elastic.clients.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:137)
2022/02/11 20:19:43 - Elasticsearch bulk insert.0 - 	at co.elastic.clients.json.JsonpDeserializer.deserialize(JsonpDeserializer.java:75)
2022/02/11 20:19:43 - Elasticsearch bulk insert.0 - 	at co.elastic.clients.json.ObjectBuilderDeserializer.deserialize(ObjectBuilderDeserializer.java:79)
2022/02/11 20:19:43 - Elasticsearch bulk insert.0 - 	at co.elastic.clients.json.DelegatingDeserializer$SameType.deserialize(DelegatingDeserializer.java:43)
2022/02/11 20:19:43 - Elasticsearch bulk insert.0 - 	at co.elastic.clients.transport.rest_client.RestClientTransport.decodeResponse(RestClientTransport.java:328)
2022/02/11 20:19:43 - Elasticsearch bulk insert.0 - 	at co.elastic.clients.transport.rest_client.RestClientTransport.getHighLevelResponse(RestClientTransport.java:294)
2022/02/11 20:19:43 - Elasticsearch bulk insert.0 - 	at co.elastic.clients.transport.rest_client.RestClientTransport.performRequest(RestClientTransport.java:147)
2022/02/11 20:19:43 - Elasticsearch bulk insert.0 - 	at co.elastic.clients.elasticsearch.ElasticsearchClient.bulk(ElasticsearchClient.java:310)
2022/02/11 20:19:43 - Elasticsearch bulk insert.0 - 	at org.pentaho.di.trans.steps.elasticsearchbulk.ElasticSearchBulk.processBatch(ElasticSearchBulk.java:321)
2022/02/11 20:19:43 - Elasticsearch bulk insert.0 - 	at org.pentaho.di.trans.steps.elasticsearchbulk.ElasticSearchBulk.indexRow(ElasticSearchBulk.java:214)
2022/02/11 20:19:43 - Elasticsearch bulk insert.0 - 	... 3 more
2022/02/11 20:19:43 - Elasticsearch bulk insert.0 - Caused by: java.lang.ClassCastException: org.glassfish.json.JsonProviderImpl cannot be cast to jakarta.json.spi.JsonProvider
2022/02/11 20:19:43 - Elasticsearch bulk insert.0 - 	at jakarta.json.spi.JsonProvider.provider(JsonProvider.java:73)
2022/02/11 20:19:43 - Elasticsearch bulk insert.0 - 	... 34 more

i found jakarta.json.spi.JsonProvider 

    private static final String DEFAULT_PROVIDER
            = "org.glassfish.json.JsonProviderImpl";
    public static JsonProvider provider() {
        ServiceLoader<JsonProvider> loader = ServiceLoader.load(JsonProvider.class);
        Iterator<JsonProvider> it = loader.iterator();
        if (it.hasNext()) {
            return it.next();
        }
        try {
            Class<?> clazz = Class.forName(DEFAULT_PROVIDER);
            return (JsonProvider) clazz.newInstance();
        } catch (ClassNotFoundException x) {
            throw new JsonException(
                    "Provider " + DEFAULT_PROVIDER + " not found", x);
        } catch (Exception x) {
            throw new JsonException(
                    "Provider " + DEFAULT_PROVIDER + " could not be instantiated: " + x,
                    x);
        }
    }

in Kettle  ENV 

 Iterator<JsonProvider> it = loader.iterator(); 

is null,so init  DEFAULT_PROVIDER

**Comment by Xupi** [comment]
Hi, I had similar issue, mostly coming from dependency version mismatch. How does Your dependencies look like?

**Comment by hyjlmj** [comment]
> Hi, I had similar issue, mostly coming from dependency version mismatch. How does Your dependencies look like?

my kettle version is pdi-ce-9.2.0.0-290

pom elasticsearch-java jackson-databind version

`<elasticsearch.version>7.17.0</elasticsearch.version>`

```xml
   <dependency>
      <groupId>co.elastic.clients</groupId>
      <artifactId>elasticsearch-java</artifactId>
      <version>${elasticsearch.version}</version>
    </dependency>


  <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
      <version>2.13.1</version>
    </dependency>
```

**Comment by Xupi** [comment]
Take a look here -> https://stackoverflow.com/questions/47022653/provider-org-glassfish-json-jsonproviderimpl-not-found-at-javax-json-spi-jsonpro or here -> https://stackoverflow.com/questions/33083050/provider-org-glassfish-json-jsonproviderimpl-not-found

Looks like You have all the dependencies, but it could be a problem with glassfish dependency, that You are using:

```xml
<dependency>
	<groupId>org.glassfish</groupId>
	<artifactId>javax.json</artifactId>
</dependency>
```
but You should use:
```xml
<dependency>
	<groupId>org.glassfish</groupId>
	<artifactId>jakarta.json</artifactId>
</dependency>
```

or You are missing implementation as pointed in second stackoverflow link. I don't know what dependencies kettle provide, but maybe this will show You where to look.

**Comment by hyjlmj** [comment]
> Take a look here -> https://stackoverflow.com/questions/47022653/provider-org-glassfish-json-jsonproviderimpl-not-found-at-javax-json-spi-jsonpro or here -> https://stackoverflow.com/questions/33083050/provider-org-glassfish-json-jsonproviderimpl-not-found
> 
> Looks like You have all the dependencies, but it could be a problem with glassfish dependency, that You may be using:
> 
> ```
> <dependency>
> 	<groupId>org.glassfish</groupId>
> 	<artifactId>javax.json</artifactId>
> </dependency>
> ```
> 
> but You should use:
> 
> ```
> <dependency>
> 	<groupId>org.glassfish</groupId>
> 	<artifactId>jakarta.json</artifactId>
> </dependency>
> ```
> 
> or You are missing implementation as pointed in second stackoverflow link. I don't know what dependencies kettle provide, but maybe this will show You where to look.


Thank you, I use pom like this

 
    <dependency>
      <groupId>co.elastic.clients</groupId>
      <artifactId>elasticsearch-java</artifactId>
      <version>${elasticsearch.version}</version>
    </dependency>

    
    <dependency>
      <groupId>org.glassfish</groupId>
      <artifactId>jakarta.json</artifactId>
      <version>2.0.1</version>
    </dependency>

    
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
      <version>2.13.1</version>
    </dependency>

is ok! 

Thank you very much
