### ISSUE TITLE
`SuggestFuzziness` requires optional attributes to be set.

### ISSUE THREAD

**Issue by sothawo** [elastic/elasticsearch-java#162]
Client version 7.17.0

[co.elastic.clients.elasticsearch.core.search.SuggestFuzziness](https://github.com/elastic/elasticsearch-java/blob/main/java-client/src/main/java/co/elastic/clients/elasticsearch/core/search/SuggestFuzziness.java#L65-L71) requires values for all it's properties. 

According to [the documentation](https://www.elastic.co/guide/en/elasticsearch/reference/8.0/search-suggesters.html#fuzzy) these are optional and it should be possible to omit them.

**Comment by d2a-jbroek** [comment]
Still a problem in 7.17.2 and 8.1.3.
