### ISSUE TITLE
Missing support for match_only_type

### ISSUE THREAD

**Issue by rokkolesa** [elastic/elasticsearch-java#164]
The API seems to be missing support for the `match_only_text` field type.
The error we get is:
<img width="479" alt="image" src="https://user-images.githubusercontent.com/6898398/154929730-62f495c6-d2c0-4c51-8656-378b90f612ee.png">

This seems to be somewhat related to #142, but we have a static type `match_only_text`.
It seems the enum is missing in `Property.Kind`.
Or is there some other way of parsing the response?

**Comment by swallez** [comment]
This has been fixed in the API specification in https://github.com/elastic/elasticsearch-specification/pull/1549 and in the Java client in https://github.com/elastic/elasticsearch-java/commit/2b5f3d2211d3c949b0d8e404e8582ab66faf762d. Thanks for the report.
