### ISSUE TITLE
Missing support for custom options of custom highlighter

### ISSUE THREAD

**Issue by leeuwr** [elastic/elasticsearch-java#168]
The RestHighLevelClient allows for custom options for a highlighted field. In DSL:

```
"highlight": {
    "type": "my-custom-highlighter",
    "highlight_query": {[..]}
    "order": "score",
    "fields": {
      "my-field": {
        "options": {
          "foo": "bar"
        }
      }
    }
}
``` 

In Java with RHLC that can be done with:

```java
final HighlightBuilder.Field highlightField = new HighlightBuilder.Field("my-field")
        .options(Map.of("foo", "bar"));
```

However, no such support for custom options exist in new Java client. Any plans to re-introduce that functionality? 

---

Implementation in RHLC can be found in `org/elasticsearch/search/fetch/subphase/highlight/AbstractHighlighterBuilder.java`:
```java
[..]
    /**
     * Allows to set custom options for custom highlighters.
     */
    @SuppressWarnings("unchecked")
    public HB options(Map<String, Object> options) {
        this.options = options;
        return (HB) this;
    }
[..]
```

**Comment by l-trotta** [comment]
[issue 252](https://github.com/elastic/elasticsearch-java/issues/252) has been resolved and merged, here's the [documentation](https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/current/variant-types.html#variant-types-custom) on how to implement custom highlighters in the new Java Rest API Client
