### ISSUE TITLE
Multisearch requests in new Java API do not support “sort” or “searchAfter” properties

### ISSUE THREAD

**Issue by AJovcheska** [elastic/elasticsearch-java#170]
SearchRequest offers the possibility to set the 'sort' or 'searchAfter' property, but in MSearchRequest this is missing. It is not available in MultisearchHeader not MultisearchBody in the RequestItem.

**Comment by jerryguowei** [comment]
We also got the same issues. Actually there are many properties  missing in the MultisearchBody. For example `version`, `source` etc.  Is there any plan to add those properties as well?

When using HLRC, we are using `org.elasticsearch.action.search.MultiSearchRequest`, which has code to write the header and body
```
    public static byte[] writeMultiLineFormat(MultiSearchRequest multiSearchRequest, XContent xContent) throws IOException {
        ByteArrayOutputStream output = new ByteArrayOutputStream();
        for (SearchRequest request : multiSearchRequest.requests()) {
            try (XContentBuilder xContentBuilder = XContentBuilder.builder(xContent)) {
                writeSearchRequestParams(request, xContentBuilder);
                BytesReference.bytes(xContentBuilder).writeTo(output);
            }
            output.write(xContent.streamSeparator());
            try (XContentBuilder xContentBuilder = XContentBuilder.builder(xContent)) {
                if (request.source() != null) {
                    request.source().toXContent(xContentBuilder, ToXContent.EMPTY_PARAMS);
                } else {
                    xContentBuilder.startObject();
                    xContentBuilder.endObject();
                }
                BytesReference.bytes(xContentBuilder).writeTo(output);
            }
            output.write(xContent.streamSeparator());
        }
        return output.toByteArray();
    }

```

We can see that `  request.source().toXContent(xContentBuilder, ToXContent.EMPTY_PARAMS);` is to write code to body, and the source() actually returns`org.elasticsearch.search.builder.SearchSourceBuilder`, in other words, all the parameters in the `SearchSourceBuilder` builder should be included in the body.

**Comment by AJovcheska** [comment]
Update from my side: I checked out the repo and saw that the tag for 7.17.4 was done on May 3rd, and the task was merged on May 24. So the changes are not present in 7.17.x release. Can you please release them under 7.17?
