### ISSUE TITLE
index request fails when using refresh=wait_for

### ISSUE THREAD

**Issue by roytmana** [elastic/elasticsearch-java#18]
`
final IndexResponse ir = client.index(builder -> builder.index("test").id("1")
          .value(new JsonMap("name", "alex1"))
          .refresh(Json.createValue("wait_for")));
`

fails with 
`
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Unknown value for refresh: [\"wait_for\"]."}],"type":"illegal_argument_exception","reason":"Unknown value for refresh: [\"wait_for\"]."},"status":400}
`
I am not sure I am passing refresh parameter correctly but I could not find any examples

on another note. is this client ready for production use or it is in experimental state?
I really would like to get off low level REST client but not sure what this client's status is
would appreciate any info regarding this project status

**Comment by swallez** [comment]
Hey @roytmana! Thanks for your interest in the new client! The current release is still very experimental and incomplete.

We will release a beta version in the coming days that will be much more finalized and tested. I'll make sure your example is included in the tests.

**Comment by swallez** [comment]
@roytmana we've released version 7.15.0 (beta) last Friday, which includes a [test for the issue you reported](https://github.com/elastic/elasticsearch-java/blob/fed933b60a3871da7cd6515384cc64d2d011a3b8/java-client/src/test/java/co/elastic/clients/elasticsearch/end_to_end/RequestTest.java#L230).

Note that `JsonValue` is used in places where either our API specification is incomplete or where the code generation doesn't yet support the target data structure and will utimately be replaced by a strongly typed parameter.

We're working on removing all of them, and also on some "getting started" docs for this new client.
