### ISSUE TITLE
[Feature Request] Report new elasticsearch-java versions as GitHub Tags and Releases

### ISSUE THREAD

**Issue by cyrille-leclerc** [elastic/elasticsearch-java#188]
### Description

I don't know where to see the releases of the elasticsearch-java library. It's a dependabot message that informs me (e.g. [here](https://github.com/jenkinsci/opentelemetry-plugin/pull/352)).

The common way to find this piece of information on GitHub, the [tags](https://github.com/elastic/elasticsearch-java/tags) screen only reports 7.x versions (the last reported being 7.17.1).

Could the elasticsearch-java client project report its version with its release notes as GitHub [tags](https://github.com/elastic/elasticsearch-java/tags) and [releases](https://github.com/elastic/elasticsearch-java/releases)?

**Comment by swallez** [comment]
Dependabot certainly gets its information from [Maven Central](https://search.maven.org/artifact/co.elastic.clients/elasticsearch-java).

Regarding tags, they should be added automatically by the Elastic Stack release manager. I'll reach out to our infra team to see why 8.0 was no tagged.
