### ISSUE TITLE
Migration questions

### ISSUE THREAD

**Issue by hejcz** [elastic/elasticsearch-java#20]
Hi,

I've tried to replace deprecated high level elasticsearch client with this client and have couple questions.

1. Is this client stable? README says it's status is work in progress. Is it ready to be used on production?
2. Is there a replacement for BulkProcessor? It had many options I can't find where to set in this client like flush interval or backoff policy.
3. RestClient has runtime scope but it seems to be impossible to create ElasticsearchClient without it? Wouldn't it be better to make elasticsearch-rest-client a compile dependency?

**Comment by swallez** [comment]
Hi @hejcz! The current release of this new client is indeed still experimental and incomplete. However we're about to release a beta version in the coming days that will be much more finalized and tested, and where indeed the rest client is no more runtime scope.

There will be no direct replacement for BulkProcessor in this beta release, this is however in the plans and will come later.

I'll post updates here.

**Comment by swallez** [comment]
We've released version 7.15.0 (beta) last Friday, which includes a test for the issue you reported, it's available on Maven Central.

It's much more stable than the experimental snapshot you've been testing but still doesn't have complete API coverage.

**Comment by ArchCST** [comment]
> We've released version 7.15.0 (beta) last Friday, it's available on Maven Central.
> 
> It's much more stable than the experimental snapshot you've been testing but still doesn't have complete API coverage.

Hi,

I'm wondering what is the oldest es version are supported by 7.15.0(beta), hence we are still on es7.7.0 somehow..

**Comment by swallez** [comment]
Version 7.16.0 was released yesterday. It has full API coverage except two API endpoints that have binary payloads (we target 7.17 for these).

The Java API client will work with Elasticsearch 7.14 and up, although we only provide forward-compatibility guaranties for later minor versions of the server (i.e. the 7.16 client will work with the 7.17 server).
