### ISSUE TITLE
Unable to set query parameters (like `filter_path`) in search requests

### ISSUE THREAD

**Issue by oliverlockwood** [elastic/elasticsearch-java#203]
### Description

In the RHLC, which this client is meant to replace, you can make a call like:
```java
restHighLevelClient.search(searchRequest, requestOptions);
```
It is possible to customise requestOptions such that a query param is added to REST requests going to Elasticsearch, e.g.
```
RequestOptions requestOptions = RequestOptions.DEFAULT.toBuilder()
        .addParameter("filter_path", "-hits.hits._source.annotations")
        .build();
```
This feature was added by https://github.com/elastic/elasticsearch/pull/67802 and its respective back ports.

In the new Java client, you make a call like:
```java
esClient.search(searchRequest, MyDocument.class)
```

I have not been able to find any way to customise the `SearchRequest` to set a parameter like `filter_path`.  Please would you advise me how to do this; and if it's not currently possible, then please treat this as a feature request!  It would be unfortunate to be blocked from upgrading to the new Java client, and thereby blocked from upgrading our applications beyond Java 8, simply because the new Java client is less capable than the existing RHLC.

**Comment by swallez** [comment]
You can achieve the same with the transport options:

```java
TransportOptions filterOptions = esClient._transport().options().with(b -> b
    .setParameter("filter_path", "-hits.hits._source.annotations")
);

esClient.withTransportOptions(filterOptions).search(searchRequest, MyDocument.class);
```

The notation may feel a bit clunky by having to look up `_transport()` because of #206 that will improve it.

**Comment by swallez** [comment]
> and thereby blocked from upgrading our applications beyond Java 8

@oliverlockwood I'm curious: can you elaborate on this? As far as I know HLRC should work just fine with any Java8+. Or are you encountering the [split-package issue](https://github.com/elastic/elasticsearch/issues/81984)?

**Comment by oliverlockwood** [comment]
@swallez thank you very much for providing this information on `TransportOptions` - I'll give it a go.

Yes, we had been encountering the split-package issue.  I can't find the comment just now, but I'm sure that last time I looked it up the response from Elastic was that to avoid the split-package issue, it was necessary to switch to using the new Java client.

From the link that you provided in your last message, do I presume that the split-package issue has actually also been fixed for the legacy RHLC, via a package rename on the server-side classes?

**Comment by oliverlockwood** [comment]
Sounds like we don't have much choice but to upgrade in due course!  Hopefully you will then fix the blocking issues which make the new client unusable in some cases, e.g.:
- https://github.com/elastic/elasticsearch-java/issues/160
- https://github.com/elastic/elasticsearch-java/issues/150
- https://github.com/elastic/elasticsearch-java/issues/124

Otherwise we're somewhat stuck.
