### ISSUE TITLE
[Documentation] Document how to use the CreateIndexRequest, particularly the mappings

### ISSUE THREAD

**Issue by cyrille-leclerc** [elastic/elasticsearch-java#208]
### Description

Could you please provide an example on how to use the `CreateIndexRequest` API, particularly how to define the mappings?

I didn't catch how to use the `CreateIndexRequest.Builder#mappings()` API to do something like

```
PUT /logs
{"mappings": {
    "properties": {
      "@timestamp": { "type": "date" },
      "message": { "type": "match_only_text" }
    }
  }
}
```

**Comment by swallez** [comment]
Good catch, `match_only_text` is missing from the API specification. I opened https://github.com/elastic/elasticsearch-specification/issues/1548 to fix this.

If you use `text` instead, that would be:

```java
client.indices().create(r -> r
    .index("logs")
    .mappings(m -> m
        .properties("@timestamp", p -> p.date(d -> d))
        .properties("message", p -> p.text(t -> t))
    )
);
```

**Comment by swallez** [comment]
This has been fixed in the API specification in https://github.com/elastic/elasticsearch-specification/pull/1549 and in the Java client in https://github.com/elastic/elasticsearch-java/commit/2b5f3d2211d3c949b0d8e404e8582ab66faf762d.
