### ISSUE TITLE
Add support for Create Index settings and mappings from a Map or JSON object

### ISSUE THREAD

**Issue by logicpeters** [elastic/elasticsearch-java#232]
### Description

In migrating from the high level REST client to the new java client, I found there is a feature that does not appear to be supported when creating indices:

https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/java-rest-high-create-index.html

The client used to be able to pass in the index settings and mappings as a Map object using the calls request.settings(map) and request.mappings(map).  This made it so that we could read a json file from our resources directory which had all these mappings, convert this to a Map (using the jackson library), and add to the CreateIndexRequest.

In the new Java client, settings are added individually from within the builder.  There does not seem to be the equivalent of adding these settings from either a Map or a JSON formatted object.  My implementation has quite a large set of mappings and settings, so breaking this down into builder commands is very awkward.

Its possible to work around this using the low level client directly, but it would be nice to have the new client support tbe previous feature.

**Comment by Molder221** [comment]
CreateIndexRequest request = CreateIndexRequest.of(
                (r -> r.index("index_name")
                        .mappings(m -> m.withJson(mappingStream))
                        .settings(s -> s.withJson(settingsStream))
                )
        );

**Comment by keep-sunshine** [comment]
> 

How should I set the custom analyzer  by  the `IndexSettings`

**Comment by AngelaFabregues** [comment]
Same issue here to provide the index settings for elastiknn plugin while keeping the rest of the settings implemented using elasticsearch-java.

**Comment by swallez** [comment]
API objects can be created with a mix of Java code and are JSON. See the explanation and examples for this feature at https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/current/loading-json.html

Regarding plugin settings, adding support for this is in progress and will be part of the next release.
