### ISSUE TITLE
elasticsearch-java support Pinned Query?

### ISSUE THREAD

**Issue by X-rapido** [elastic/elasticsearch-java#233]
### Description

I did not find support  pinned query in the `HLRC` version

> https://github.com/elastic/elasticsearch/issues/83238

in `elasticsearch-java`  can support?

**Comment by l-trotta** [comment]
Hey, sure it does! For example, here is how to write same[ pinned query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-pinned-query.html#_example_request) found in the [official documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-pinned-query.html) using the java client:

```
        SearchResponse<Object> pinnedQuery = esClient.search(s -> s
                .index("index")
                .query(q -> q
                    .pinned(p -> p
                        .ids(List.of("1","4","100"))
                        .organic(o -> o
                            .match(m -> m
                                .field("description")
                                .query("iphone")))))
            , Object.class);
```
