### ISSUE TITLE
Missing configuration property MultiTermsAggregation.size

### ISSUE THREAD

**Issue by JavaSaBr** [elastic/elasticsearch-java#250]
### Java API client version: 8.1.3

No possibility to configure additional settings (like **size**) of multi terms aggregation requests in the java client.
The list of such parameters you can see there:
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-multi-terms-aggregation.html#search-aggregations-bucket-multi-terms-aggregation-parameters

**Comment by mikelinhas** [comment]
This is missing in previous versions too. From **7.16** up.

**Comment by mcrtricolor** [comment]
Same problem here. Also you can't sort the multiTerms query aggregation in java.

**Comment by l-trotta** [comment]
Thanks for the report :) the problems related to MultiTerms Aggregation configuration have already been fixed in newer versions of the client, so I'm closing this.
