### ISSUE TITLE
请问如何打印一个可执行的DSL语句

### ISSUE THREAD

**Issue by KuanKuanya** [elastic/elasticsearch-java#280]
ElasticSearchClient客户端最新版的

**Comment by swallez** [comment]
Please write issues in English, which is the project's language.

Translating the issue title gives "How to print an executable DSL statement". This has been answered here https://github.com/elastic/elasticsearch-java/issues/97#issuecomment-1008604515

We've also recently implemented `toString` on API objects, and this will be included in the next version (see #269).

**Comment by KuanKuanya** [comment]
thanks！When will the next version be released！
