### ISSUE TITLE
Serializing method in query builders in order to be able to debug with logs

### ISSUE THREAD

**Issue by idrissneumann** [elastic/elasticsearch-java#287]
### Description

In the last versions of clients we were able to log the JSON query in our logs in order to copy/paste the json query in Kibana dev tools or `curl` or something else and execute it (like we're able to do so with SQL queries and Hibernate/JPA or other java DSL for other databases). Of course those logs aren't enabled h24, only when we're working on localhost or debug a staging environment for example.

I dig a little bit into it and I was able to try a method like that: 

```java
static String toJson(final BoolQuery.Builder builder, JacksonJsonpMapper mapper) {
    JsonFactory factory = new JsonFactory();
    StringWriter jsonObjectWriter = new StringWriter();
    try {
      JsonGenerator generator =
          new JacksonJsonpGenerator(factory.createGenerator(jsonObjectWriter));
      builder.build().serialize(generator, mapper);
      generator.close();
      return jsonObjectWriter.toString();
    } catch (IOException e) {
      return null;
    }
}

default String toJson(final BoolQuery.Builder builder) {
    return toJson(builder, getMapper());
}
```

And I were able to test it like that and it did works as expected:

```java
@Test
public void toJsonTest_Nominal() {
    // Given
    BoolQuery.Builder qb = new BoolQuery.Builder();
    qb.minimumShouldMatch("1");
    qb.should(q -> q.term(t -> t.field("field").value("val")));

    // When
    String json = toJson(qb, new JacksonJsonpMapper());

    // Then
    assertThat(json).isNotBlank().isEqualTo(
        "{\"minimum_should_match\":\"1\",\"should\":[{\"term\":{\"field\":{\"value\":\"val\"}}}]}");
}
```

The problem is the builder immutability that will raise an `IllegalStateException` when we're both logging and using the builder in a searchrequest. We can reproduce the problem with this test:

```java
@Test
public void toJsonTest_MultipleTimes() {
    // Given
    BoolQuery.Builder qb = new BoolQuery.Builder();
    qb.minimumShouldMatch("1");
    qb.should(q -> q.term(t -> t.field("field").value("val")));

    // When
    String json = toJson(qb, new JacksonJsonpMapper());
    String json2 = toJson(qb, new JacksonJsonpMapper());

    // Then
    assertThat(json).isNotBlank().isEqualTo(
            "{\"minimum_should_match\":\"1\",\"should\":[{\"term\":{\"field\":{\"value\":\"val\"}}}]}").isEqualTo(json2);
}
```

The serialization should be idempotent and shouldn't be an issue to call it multiple times so I suggest to implement a `serialize` method directly in the builder.

Thanks in advance.

**Comment by fabian-froehlich** [comment]
In our application I wrote a util function
```
    String toJson(JsonpSerializable obj) {
        StringWriter stringWriter = new StringWriter();
        try (JsonGenerator generator = new JacksonJsonpGenerator(mapper.createGenerator(stringWriter))) {
            JsonbJsonpMapper mapper = new JsonbJsonpMapper();
            obj.serialize(generator, mapper);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        return stringWriter.toString();
    }
```
If you have a `Builder` you can use it to build the immutable `query` and print it:
```
Query query = new BoolQuery.Builder().build()._toQuery();
toJson(query);
```

**Comment by idrissneumann** [comment]
Thanks @fabian-froehlich . That's what I'm doing right now and it works well.

I wanted to be able to export it multiple times during the builder construction (in order to have all json queries each time we add something in the builder during the process). But a final log just after building the final query is enough.

I close this ticket for now has I think I have everything I need for now, thanks for your help :)
