### ISSUE TITLE
MultisearchBody Should Support Highlight and Source

### ISSUE THREAD

**Issue by rsahlstrom** [elastic/elasticsearch-java#288]
### Description

The MultisearchBody does not let you do everything you can when making manually JSON calls. For example, this SDK does not allow you to specify:

* highlight
* _source.includes or _source.excludes

As a result, I'm doing multiple SearchRequests calls instead of a single msesarch request.

**Comment by swallez** [comment]
This has been fixed in PR #292, backported to version 8.2 in PR #293 and to version 7.17 in PR #294.
