### ISSUE TITLE
Cannot create index with mappings settings

### ISSUE THREAD

**Issue by jaizpuru** [elastic/elasticsearch-java#297]
### Java API client version

8.2.2

### Java version

8

### Elasticsearch Version

8.2.2

### Problem description

The following code is expected to trigger an index creation in the target server. Instead, the error response below is received

```
RestClient restClient = RestClient.builder(new HttpHost("localhost", 9200)).build();
ElasticsearchTransport transport = new RestClientTransport(restClient, new JacksonJsonpMapper());

CreateIndexRequest request = new CreateIndexRequest.Builder().index("name")
    .settings(s -> s.mappings(m -> m.totalFields(totalFields -> totalFields.limit(1001))))
    .build();

new ElasticsearchClient(transport).indices().create(request);
```

Response:

> [es/indices.create] failed: [illegal_argument_exception] unknown setting [index.mappings.total_fields.limit] did you mean any of ...

**Comment by KnowledgeGarden** [comment]
In earlier versions, there was a clean api with which to load JSON mappings. It's gone and, post 7, no documentation. Surely there is a way to load JSON mappings in recent versions.

**Comment by yoh1496** [comment]
Hi, I have same problem.
It is written in below document that mapping limit settings should place with parameter `index.mapping.*` 

https://www.elastic.co/guide/en/elasticsearch/reference/8.2/mapping-settings-limit.html

So, this line should be change like this.

https://github.com/elastic/elasticsearch-java/blob/main/java-client/src/main/java/co/elastic/clients/elasticsearch/indices/IndexSettings.java#L1997

```
op.add(Builder::mappings, MappingLimitSettings._DESERIALIZER, "mapping");
```

Could you change this?

**Comment by swallez** [comment]
This is an issue in the [API specification](https://github.com/elastic/elasticsearch-specification/blob/1f82a03fec4970507c041d2f210a7cf5106c3906/specification/indices/_types/IndexSettings.ts#L154) used to produce the Java code: `mappings` should be `mapping`.

The fix will be included in the next 8.x and 7.17.x releases.

**Comment by swallez** [comment]
Closing, as the same issue has been reported in #295
