### ISSUE TITLE
MultiSearchBody should support highlight,searchAfter,sort...

### ISSUE THREAD

**Issue by Dyqer** [elastic/elasticsearch-java#307]
### Java API client version

7.17

### Java version

8

### Elasticsearch Version

7.1

### Problem description

MultiSearchBody should contains all params which searchRequest supported

**Comment by jerryguowei** [comment]
It looks like this is already supported in the latest code, please check this commit: 
https://github.com/elastic/elasticsearch-java/commit/16d315f9f56cc3783198012f1249d53d5e6f0b41

**Comment by swallez** [comment]
Thanks @jerryguowei. Indeed it will be in 7.17.5. The corresponding commit is https://github.com/elastic/elasticsearch-java/commit/d2f6886d7ac7eb045f4834cdd6e94dd4c8a33a5f
