### ISSUE TITLE
Missing fields in `MultiTermsAggregation`

### ISSUE THREAD

**Issue by swallez** [elastic/elasticsearch-java#319]
`MultiTermsAggregation` is missing a number of fields:
* `collect_mode`,
* `order`,
* `min_doc_count`,
* `shard_min_doc_count`,
* `shard_size`,
* `show_term_doc_count_error`,
* `size`

Closes #310 reported by @andreluiz1987 by rewording it as an API-specification related issue.

**Comment by mcrtricolor** [comment]
Hi, do you know in which version of the java api will this be available? Thanks for your work!
