### ISSUE TITLE
Reorder key-values in meta header to match other clients

### ISSUE THREAD

**Issue by sethmlarson** [elastic/elasticsearch-java#334]
In the [`getClientMeta` function](https://github.com/elastic/elasticsearch-java/blob/main/java-client/src/main/java/co/elastic/clients/transport/rest_client/RestClientOptions.java#L186) the order of key-value pairs is es, jv, hl, t. However the header value should be ordered with es, jv, and t as the first 3 keys.

- Current: `es=X,jv=X,hl=2,t=X,...`
- Proposed: `es=X,jv=X,t=X,hl=2,...`

**Comment by Ankit-Khachane** [comment]
Hi @sethmlarson  I want to contribute to this project,
If this has not been picked up yet can I take this up?

**Comment by sethmlarson** [comment]
@Ankit-Khachane It doesn't appear to be picked up, you definitely can.
