### ISSUE TITLE
InfoResponse MissingRequiredPropertyException

### ISSUE THREAD

**Issue by cliff-sizer-insightsoftware-com** [elastic/elasticsearch-java#335]
### Java API client version

8.3.1

### Java version

11

### Elasticsearch Version

8.3.1

### Problem description

MissingRequiredPropertyException being thrown by the co.elastic.clients.elasticsearch.core.InfoResponse because "build_flavor" : "default" has disappeared in ES 8.3.1

**Comment by dadoonet** [comment]
I'm seeing the same error. 

The workaround until it's fixed is:

```java
ApiTypeHelper.DANGEROUS_disableRequiredPropertiesCheck(true);
InfoResponse info = client.info();
ApiTypeHelper.DANGEROUS_disableRequiredPropertiesCheck(false);
```

**Comment by sethmlarson** [comment]
Thanks @dadoonet for providing a work-around. I've [created an issue](https://github.com/elastic/elasticsearch/issues/88318) upstream to fix this issue.
