### ISSUE TITLE
co.elastic.clients.elasticsearch.core.search.Hit.sort should contains type information.

### ISSUE THREAD

**Issue by Dyqer** [elastic/elasticsearch-java#336]
### Java API client version

all

### Java version

14

### Elasticsearch Version

7.1.1

### Problem description

Sometimes we need to resort the response hits (e.g. merge response from two cluster), the type of sort fields is important, but it just `List<String>` now

**Comment by l-trotta** [comment]
Hey, thanks for the report! I tested it using the newer 7.17 version querying a non string field and `sort` showed the correct type, let me know if this still occurs to you.

**Comment by l-trotta** [comment]
closing this, feel free to reopen in case there are any updates.
