### ISSUE TITLE
 java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory

### ISSUE THREAD

**Issue by LeoLuo21** [elastic/elasticsearch-java#340]
### Java API client version

8.3.2

### Java version

11

### Elasticsearch Version

8.3.1

### Problem description

When creating ElasticsearchClient, There is something wrong. The Exception is below:
**Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory**
Do i need to import extra dependency of apache-commons-logging?

**Comment by swallez** [comment]
You should not need to, as commons logging should be imported by transitive dependencies via `elasticsearch-rest-client`. Maybe you have some specific version or dependency overrides in your build definition?

**Comment by l-trotta** [comment]
Unfortunately we cannot move on with reproducing without more information, so I'm closing this for now, feel free to comment if the issue persists!
