### ISSUE TITLE
StoreStats uses int for sizeInBytes field

### ISSUE THREAD

**Issue by lzz118** [elastic/elasticsearch-java#347]
### Java API client version

7.17.3

### Java version

java 8

### Elasticsearch Version

7.17.3

### Problem description

Currently, the sizeInBytes field in the StoreStats object is create with type int, therefore if the index has over 15GB in the storage size, this field will become overflow.

https://javadoc.io/doc/co.elastic.clients/elasticsearch-java/7.17.3/co/elastic/clients/elasticsearch/_types/StoreStats.html

<img width="1271" alt="image" src="https://user-images.githubusercontent.com/2018525/178522866-01997e51-2f28-4278-9ea6-209cfec28698.png">

This issue has made the client library useless for our use case and we have to go back to using the now deprecated version of older java clients.

Please take a look

**Comment by l-trotta** [comment]
fixed with #759 , the issue will be solved in the next release.
