### ISSUE TITLE
Scroll API support

### ISSUE THREAD

**Issue by gquintana** [elastic/elasticsearch-java#36]
How do you implement the equivalent of 
```
POST /_search/scroll 
{
    "scroll" : "1m", 
    "scroll_id" : "DXF1ZXJ5QW5kRmV0Y2gBAAAAAAAAAD4WYm9laVYtZndUQlNsdDcwakFMNjU1QQ==" 
}
```
with this library?

Then the following code:
```
client.clearScroll(new ClearScrollRequest.Builder().scrollId(scrollId).build());
```
where scrollId is not null, raises an ApiException with root cause error:
```
Validation Failed: 1: no scroll ids specified;"
```
Why?

**Comment by mindscratch** [comment]
So right now, since only a "scroll" duration can be specified when building the search request and no way to set the `scrollId` after getting the first page of results, we'd have to use the REST client correct?

**Comment by swallez** [comment]
@mindscratch correct, the `_search/scroll` API endpoint is missing in version 7.15 of the java client. Is has been added in the upcoming 7.16.

Furthermore the issues reported by @gquintana have been solved too ([see test](https://github.com/elastic/elasticsearch-java/blob/2262aab24bc5f6a16e62a2f5c66edf47b5dfb00e/java-client/src/test/java/co/elastic/clients/elasticsearch/end_to_end/RequestTest.java#L302-L319)).

For the nasty details, this came from the fact that in this API endpoint Elasticsearch will ignore the `scroll_id` request parameter when there is a body, even if doesn't contain a `scroll_id` property. And we were sending the request parameter with an empty body, hence this error. We've now send `scroll_id` as a request body property and Elasticsearch is happy 😉

**Comment by mindscratch** [comment]
@swallez thanks for the follow-up, is there an ETA for when the 7.16.0 version will be released?

**Comment by swallez** [comment]
@mindscratch I can't give an exact date, but it should be out in the next two weeks!
