### ISSUE TITLE
Adding index block uses Enum name rather than value

### ISSUE THREAD

**Issue by jdbranham** [elastic/elasticsearch-java#37]
If I'm understanding the syntax correctly, this should enable the write block on an index - 

```
client.indices().addBlock(b -> b.index(sourceIndexName).block(IndicesBlockOptions.Write));
```

It results in a `PUT` operation with the enum name rather than the value.  
From Apache http wire tracing -  
```
http-outgoing-7 >> "PUT /tmp_public_id_and_name/_block/Write HTTP/1.1[\r][\n]"
```

This causes an exception -  
```
"type":"illegal_argument_exception", "reason":"No block found with name Write"
```

It works like this, so maybe this is the correct way?  
```
client.indices().putSettings(b -> b.index(sourceIndexName).settings(s -> s.blocks(w -> w.write(true))));
```

**Comment by swallez** [comment]
Thanks for the report @jdbranham! This was indeed a bug where we were incorrectly using the enum member's name as the parameter value. This has been fixed in the upcoming 7.16 release.
