### ISSUE TITLE
DataStreamsStatsResponse, total_store_size_bytes can be larger than int

### ISSUE THREAD

**Issue by Remcojansen88** [elastic/elasticsearch-java#379]
### Java API client version

8.2.2

### Java version

7

### Elasticsearch Version

8.2.2

### Problem description

Error when getting DataStreamsStatsResponse with a total_store_size_bytes value larger than int value
 
Probably needed to be fixed in specifications, and changed to a long
https://github.com/elastic/elasticsearch-specification/blob/main/specification/indices/data_streams_stats/IndicesDataStreamsStatsResponse.ts

Failed starting application co.elastic.clients.json.JsonpMappingException: 
Error deserializing co.elastic.clients.elasticsearch.indices.DataStreamsStatsResponse: jakarta.json.stream.JsonParsingException: Jackson exception: Numeric value (15273455943) out of range of int (-2147483648 - 2147483647)\n at [Source: (org.apache.http.nio.entity.ContentInputStream); line: 1, column: 133] (JSON path: total_store_size_bytes) (line no=1, column no=133, offset=-1)\n	at co.elastic.clients.json.JsonpMappingException.from0(JsonpMappingException.java:134)\n	at co.elastic.clients.json.JsonpMappingException.from(JsonpMappingException.java:121)\n	at co.elastic.clients.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:206)\n	at co.elastic.clients.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:136)\n	at

**Comment by l-trotta** [comment]
Hello, thank you for the report! You're most probably right,  `total_store_size_bytes` shouldn't be an integer, I'll confirm this and then fix the [API specification](https://github.com/elastic/elasticsearch-specification) used to produce the Java code, and once the API specification is fixed, the Java client code will be updated to resolve this issue.
