### ISSUE TITLE
SearchMvtResponse is not Json serializable

### ISSUE THREAD

**Issue by iverase** [elastic/elasticsearch-java#38]
Trying a `SearchMvtRequest` gives an error as we are trying to serialise the response to Json:

```
RestClient restClient = RestClient.builder(new HttpHost("localhost", 9200)).build());
Transport transport = new RestClientTransport(restClient, new JacksonJsonpMapper());
ElasticsearchClient client = new ElasticsearchClient(transport);
SearchMvtResponse response = client.searchMvt(
        (builder) -> builder.zoom(0).x(0).y(0).addIndex("points").field("location")
 );
```

Gives the following error:

```
Caused by: com.fasterxml.jackson.core.JsonParseException: Illegal character ((CTRL-CHAR, code 26)): only regular white space (\r, \n, \t) is allowed between tokens
```

**Comment by swallez** [comment]
Thanks for the report @iverase. The `search_mvt` API is one of the few  APIs that doesn't return JSON and the client was improperly trying to parse the binary vector tile response as JSON.

We haven't implemented binary responses yet and have removed this endpoint in the upcoming 7.16 release to avoid any confusion. It will be implemented in the next minor release.

**Comment by iverase** [comment]
Thanks @swalle for the info, it makes sense to remove it until it is implemented.
