### ISSUE TITLE
AnalyzeToken - 'positionLength' is always null

### ISSUE THREAD

**Issue by dan-king-93** [elastic/elasticsearch-java#391]
### Java API client version

7.17.6

### Java version

Open JDK 11

### Elasticsearch Version

7.17.2

### Problem description

AnalyzeToken always has positionLength as null when making an analyze request.

From looking through source code, looks you might be trying to deserialize "position_length" rather than "positionLength" as is returned in the analyze response.

**Comment by l-trotta** [comment]
Closing this as it looks like the PR containing the fix was already merged, thank you both for reporting and contributing :D
