### ISSUE TITLE
Problem with GeoPointProperty - unknown field 'index'

### ISSUE THREAD

**Issue by MaxWenzel** [elastic/elasticsearch-java#394]
### Java API client version

8.3.3

### Java version

17.0.3

### Elasticsearch Version

8.3.3

### Problem description

Hi,
according the [Documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/geo-point.html) I can use the parameter **index** for the field-type _geo_point_.
I use the Java-Client in Version 8.3.3 and a mapping like this (only a snippet):

`
"location": {
  "index": false,
  "type": "geo_point"
}
`

But the result is the following exception:

`
co.elastic.clients.json.JsonpMappingException: Error deserializing
co.elastic.clients.elasticsearch._types.mapping.GeoPointProperty: Unknown field 'index'
`

However, when I look at the class [GeoPointProperty](https://artifacts.elastic.co/javadoc/co/elastic/clients/elasticsearch-java/8.4.0/co/elastic/clients/elasticsearch/_types/mapping/GeoPointProperty.html), I don't see an index field either (I looked also in the source-code). It seems to me that this field has been forgotten.

**Comment by grib0** [comment]
Same issue here with version of client 7.17.2 and server 7.17.2. 
I'm only migrating my java client from rest hight level to the new java client and get plenty of errors like this one...

**Comment by BDelacour** [comment]
Same issue with client 7.17.16 sadly

**Comment by f-loris** [comment]
I ran into the same issue that the `GeoPointProperty` is not according to the spec. Already a PR is filed since months... 
Is there any update on that topic? It would be great to get such small issues sorted out to make the migration from high level rest client easier.
