### ISSUE TITLE
logstash putpipeline lastModified should support VALUE_NUMBER

### ISSUE THREAD

**Issue by alainbodiguel** [elastic/elasticsearch-java#398]
### Java API client version

8.4.1

### Java version

17

### Elasticsearch Version

8.4.1

### Problem description

See [discussion here](https://discuss.elastic.co/t/java-client-put-logstash-pipeline-last-modified-error/313425)

When creating a logstash pipeline, an error is raised on the lastModified attribute:

```
client.logstash().putPipeline(b -> b
                        .id(id)
                        .pipeline(p -> p
                                .description(id)
                                .lastModified(DateTime.ofEpochMilli(System.currentTimeMillis()))
...
```
```
DEBUG [2022-09-01 09:15:08,399] org.apache.http.wire: http-outgoing-1 << "{"error":{"root_cause":[{"type":"x_content_parse_exception","reason":"[1:46] [pipeline] last_modified doesn't support values of type: VALUE_NUMBER"}],"type":"x_content_parse_exception","reason":"[1:46] [pipeline] last_modified doesn't support values of type: VALUE_NUMBER"},"status":400}"
```

**Comment by l-trotta** [comment]
Hello, thanks for the report! I tried reproducing this with an updated version of the client, but it looks to me like it's working, so it was probably fixed in the meantime. If it's not the case please let me know :)

**Comment by l-trotta** [comment]
closing this, feel free to reopen in case there are any updates.
