### ISSUE TITLE
variable storedField in InnerHits class has a false API name (stored_field) should be stored_fields

### ISSUE THREAD

**Issue by 90fermat** [elastic/elasticsearch-java#409]
### Java API client version

8.x

### Java version

17

### Elasticsearch Version

8.x

### Problem description

variable storedField in InnerHits class has a false API name (stored_field). should be "stored_fields"

**Comment by l-trotta** [comment]
Hello, thanks for reporting this! This is an issue in the [API specification](https://github.com/elastic/elasticsearch-specification) used to produce the Java code, and once the API specification is fixed, the Java client code will be updated to resolve this issue.
