### ISSUE TITLE
Prefix couldn't setting to the suggester

### ISSUE THREAD

**Issue by septhirothss** [elastic/elasticsearch-java#426]
### Java API client version

7.16.3

### Java version

8

### Elasticsearch Version

7.16.3

### Problem description

In the offical document, I see the suggester could be used like this:
https://www.elastic.co/guide/en/elasticsearch/reference/7.17/search-suggesters.html

`POST art/_search?pretty
{
  "suggest": {
    "song-suggest": {
      "prefix": "nir",
      "completion": {
        "field": "suggest-4-song"
      }
    },
    "picture-suggest": {
      "prefix": "van",
      "completion": {
        "field": "suggest-4-picture"
      }
    }
  }
}`

but seems it doesn't work with elasticsearch-java, I try several kinds of writing but they all failed, and my unit test goes here:

```java
	@Test
	public void suggest() throws IOException {
		HashMap<String, FieldSuggester> map = new HashMap<>();

		//this will throws [es/search] failed: [parse_exception] missing suggestion object
		map.put("suggester1", FieldSuggester.of(fs -> fs.prefix("test")));

		//this will throws [es/search] failed: [search_phase_execution_exception] all shards failed
		map.put("suggester2", FieldSuggester.of(fs -> fs.completion(c -> c.field("title"))));
		
		//this will throws [es/search] failed: [x_content_parse_exception] [1:57] [completion] unknown field [prefix]
		map.put("suggester3", FieldSuggester.of(fs -> fs.completion(c -> c.field("title").prefix("test"))));
		
		SearchRequest build = new SearchRequest.Builder()
				.index("test-index")
				.suggest(s -> s.suggesters(map))
				.build();
		SearchResponse search = esClient.search(build, Object.class);
	}
```

So I can not used prefix in the completion suggester, and I think this situation also happen in other suggester like phrase suggester and term suggester. And if I need to specifying the text to the suggester, how could I do this?

If the problem is my understanding and use, I will very  appreciate if someone can help to me to correct my mistakes.

**Comment by l-trotta** [comment]
Hello, thank you for the report :) I wrote the original json call with the java API:

```
        esClient.search(s -> s
            .index("art")
            .suggest(sg -> sg
                .suggesters("song-suggest", ssg -> ssg
                    .prefix("nir")
                    .completion(c -> c
                        .field("suggest-4-song")))
                .suggesters("picture-suggest", psg -> psg
                    .prefix("van")
                    .completion(c -> c.field("suggest-4-picture")))), Object.class);
```

and it's working for me, so it's possible that this was an [API specification definition](https://github.com/elastic/elasticsearch-specification) that we already fixed in the newer versions of the client. Let me know if this is still an issue!
