### ISSUE TITLE
RankFeaturesProperty is missing positive_score_impact field 

### ISSUE THREAD

**Issue by gzeskas** [elastic/elasticsearch-java#450]
### Java API client version

8.7.0

### Java version

17

### Elasticsearch Version

8.5

### Problem description

RankFeaturesProperty is missing positive_score_impact field in builder.

It is possible to set `positive_score_impact ` on `RankFeatureProperty` but it's not possible to do with `RankFeaturesProperty`

But it should be possible according to elastic search documentation:

https://www.elastic.co/guide/en/elasticsearch/reference/current/rank-features.html

**Comment by l-trotta** [comment]
Hello, thank you for the report! You are correct, it's an issue with the [API specification](https://github.com/elastic/elasticsearch-specification) used to produce the Java code.

Once the API specification is fixed, the Java client code will be updated to resolve this issue.
