### ISSUE TITLE
co.elastic.clients.json.JsonpMappingException: Error deserializing co.elastic.clients.elasticsearch.indices.Storage

### ISSUE THREAD

**Issue by christian-ertl** [elastic/elasticsearch-java#458]
### Java API client version

8.5.2

### Java version

11

### Elasticsearch Version

8.4.1

### Problem description

The GetIndexRequest fails during deserialization for indexes on frozen nodes or aliases that also list such indexes:

co.elastic.clients.json.JsonpMappingException: Error deserializing co.elastic.clients.elasticsearch.indices.Storage: Invalid enum 'snapshot' (JSON path: ['partial-***************************'].settings.index.store.type) (line no=1, column no=54036, offset=-1)

**Comment by bczifra** [comment]
It looks like `snapshot` is indeed not an enum value in https://github.com/elastic/elasticsearch-java/blob/main/java-client/src/main/java/co/elastic/clients/elasticsearch/indices/StorageType.java#L36 , which seems to be triggering this deserialization exception.

**Comment by swallez** [comment]
This is an issue in the upstream API specification: indeed this enumeration is incomplete. https://github.com/elastic/elasticsearch-specification/pull/1997 will fix this, after which we can re-generate the Java client code.

This will be part of 8.6.0.
