### ISSUE TITLE
S3 based repository creation is not implemented

### ISSUE THREAD

**Issue by marcingasior** [elastic/elasticsearch-java#461]
### Java API client version

8.5.2

### Java version

17

### Elasticsearch Version

8.4.2, 8.5.2

### Problem description

The functionality of creating and retrieving information about s3 repository is missing.
Currenty RepositorySettings can only be applied to local repo. 
If repo is created with Rest request, following queries to validate the repository fails due to  "Missing required property 'RepositorySettings.location'"

**Comment by stures** [comment]
Are there any updates regarding this one? We are also interested in having this functionality.

I guess the main question is how are other types of Repositories supposed to be used? In the previous client you could send in any Json so it was easy to extend. What is the equivalent in the new one?

**Comment by l-trotta** [comment]
Hello, thanks for the report! S3 repository were recently added in this [api-spec PR](https://github.com/elastic/elasticsearch-specification/pull/2255), so it will be part of the next java client release.
