### ISSUE TITLE
当has_child.type为数组时，反序列化异常

### ISSUE THREAD

**Issue by zhanghj94** [elastic/elasticsearch-java#465]
### Java API client version

8.5.3

### Java version

11

### Elasticsearch Version

8.5.2

### Problem description

当has_child.type为数组时，反序列化异常
![image](https://user-images.githubusercontent.com/37207075/207012656-a6803fe0-a2ff-4e43-98b9-d1b84fe403fd.png)
![image](https://user-images.githubusercontent.com/37207075/207012784-b4f725c2-4891-4202-b3b8-52fd3715061f.png)
![image](https://user-images.githubusercontent.com/37207075/207012899-0c3db29b-e0d5-430b-93af-b352648f7899.png)

**Comment by l-trotta** [comment]
Hello, thanks for the report! I'm sorry it's not really clear to me what the issue is, if the problem is persisting could you please send a snippet of your java code? Thanks!

**Comment by l-trotta** [comment]
From google translate: 当has_child.type为数组时，反序列化异常 -> Deserialization exception when has_child.type is an array.
If this is what you meant, I think the `type` field only supports strings and not arrays, as per the [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-has-child-query.html#has-child-top-level-params).
