### ISSUE TITLE
Duplicate `jakarta.json` classes on runtime classpath

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch-java#47]
When running some tests using this client we run into "jar hell". That is, when bringing in the elasticsearch-java dependency it's runtime classpath includes duplicate classes from the `jakarta.json` package. This seems to be due to us pulling in both [`jakarta.json-api`](https://github.com/elastic/elasticsearch-java/blob/main/java-client/build.gradle.kts#L130) and the glassfish imlementation [`jakarta.json`](https://github.com/elastic/elasticsearch-java/blob/main/java-client/build.gradle.kts#L135) dependencies.

There's a few things going on here:

1. The glassfish implementation _includes_ the api classes, so that's what's causing the jar hell. 
2. Since the dependency is marked `implementation` it's only added to the _runtime_ classpath for consumers. Since the client exposes types from json-api through it's own API ([for example](https://github.com/elastic/elasticsearch-java/blob/main/java-client/src/main/java/co/elastic/clients/elasticsearch/security/PutUserRequest.java#L75)) this means users will run into compile errors if trying to use those types. They can "fix" this by manually adding json-api as a compile dependency.

Two options to fix here:

1. Simple remove the superfluous `json-api` dependency and make the glassfish impl `api` instead of `implementation`. This means we also leak all the `org.glassfish.json` implementation classes onto the compile classpath of any consumers.
2. Make `json-api` a `compileOnly` dependency and the glassfish impl `runtimeOnly`. This should result in only the API classes being on the compile classpath, and both API _and_ implementation classes available at runtime.

**Comment by swallez** [comment]
Thanks for spotting this! It should be fixed in db3cc23. Can you please cross-check and I'll backport to 7.16

**Comment by mark-vieira** [comment]
Changes LGTM. Thanks for addressing this @swallez!
