### ISSUE TITLE
TermVectorOption enum is missing with_positions_payloads value

### ISSUE THREAD

**Issue by sothawo** [elastic/elasticsearch-java#48]
tested with 7.16.0-SNAPSHOT (20.11.2021, 05:44)

In the TermVectorOption enum
https://github.com/elastic/elasticsearch-java/blob/main/java-client/src/main/java/co/elastic/clients/elasticsearch/_types/mapping/TermVectorOption.java the value _with_positions_payloads_ is missing (https://www.elastic.co/guide/en/elasticsearch/reference/current/term-vector.html)

**Comment by swallez** [comment]
Good catch! I've opened https://github.com/elastic/elasticsearch-specification/pull/1044 to fix this, it will be included in tomorrow's snapshot.

**Comment by swallez** [comment]
Please cross-check, it's there now: https://github.com/elastic/elasticsearch-java/blob/7.16/java-client/src/main/java/co/elastic/clients/elasticsearch/_types/mapping/TermVectorOption.java

**Comment by sothawo** [comment]
✅ works with 7.16.0 snapshot.
