### ISSUE TITLE
MultiTermLookup does not support missing field

### ISSUE THREAD

**Issue by sag-tobias-frey** [elastic/elasticsearch-java#484]
### Java API client version

8.5.2

### Java version

17

### Elasticsearch Version

8.5.2

### Problem description

The `MultiTermLookup` does not support setting the `missing` parameter which should be possible according to the documentation:

> The missing parameter defines how documents that are missing a value should be treated. By default if any of the key components are missing the entire document will be ignored but it is also possible to treat them as if they had a value by using the missing parameter.

https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-multi-terms-aggregation.html#_missing_value_3

**Comment by l-trotta** [comment]
Hello and thank you for the report! Looks like this was already fixed in most recent versions of the java client, so I'm closing this for now.
