### ISSUE TITLE
Missing geohex_grid method

### ISSUE THREAD

**Issue by mbarbet** [elastic/elasticsearch-java#488]
### Java API client version

8.6.0

### Java version

17

### Elasticsearch Version

8.6.0

### Problem description

The class co.elastic.clients.elasticsearch._types.aggregations.Aggregate is missing the geohex_grid kind (version 8.6.0).
The code in the branch 8.6 is OK but not in the tag 8.6.0.

**Comment by iverase** [comment]
It seems this was fixed here: https://github.com/elastic/elasticsearch-java/pull/432 but the commint only went to branch 8.5? so it is missing from 8.6 and main branches.

**Comment by sethmlarson** [comment]
I believe this was an issue of API generation timing. The 8.6 branch has the generated `geohex_grid` kind for `Aggregate` but the tag doesn't as it was generated before the `geohex_grid` [fix was made to elasticsearch-specification](https://github.com/elastic/elasticsearch-specification/pull/1975). Unfortunately we don't get to pick where tags land as it's done by the automatic stack release manager, this would be fixed automatically in v8.6.1.

**Comment by l-trotta** [comment]
closing this since it has been fixed.
