### ISSUE TITLE
Create a simple method to print the JSON of the search query in the new Elasticsearch java API 

### ISSUE THREAD

**Issue by amitmbm** [elastic/elasticsearch-java#498]
### Elasticsearch Version

8.6.0

### Installed Plugins

NONE

### Java Version

_bundled_

### OS Version

MacOS

### Problem Description

In the older version of Elasticsearch clients (JHLRC), it was very easy to print the Elasticsearch query, which really helps for debugging purpose, my [stackOverflow answer](https://stackoverflow.com/a/60852022/4039431) shows that its been really useful and same has ~10K views.

But now with new java API client there is no in built method to print the Elasticsearch query.

Please add a method with similar name so that its easy for folks who are migrating from older version or new to JAVA API client.

### Steps to Reproduce

NA

### Logs (if relevant)

NA

**Comment by swallez** [comment]
There are two ways to have a JSON representation of a query:

* `query.toString()`, with the caveat that the resulting string is prefixed with the class name and is limited to 10 kB. This limitation is meant to avoid accidentally printing huge objects in application logs.
* `JsonpUtils.toJsonString(query, esClient._jsonpMapper()` will return the full JSON, with no size limitation.
