### ISSUE TITLE
NPE while getting doc with GET

### ISSUE THREAD

**Issue by MikMironov** [elastic/elasticsearch-java#50]
Hi gyus!

I know that project is still in progress, but got some problems in simple usages. 
Gets NPE in ElasticsearchError.class constructor when requesting nonexistent doc through get. Fails on ```Objects.requireNonNull(builder.status, "status")``` validation 

```client.get(s -> s.index(index).id("asd"), Document.class)```

**Comment by swallez** [comment]
Thanks for the report! There was indeed an issue in 7.15, this has been fixed [and tested](https://github.com/elastic/elasticsearch-java/blob/2262aab24bc5f6a16e62a2f5c66edf47b5dfb00e/java-client/src/test/java/co/elastic/clients/elasticsearch/end_to_end/RequestTest.java#L161-L179) in the upcoming 7.16.
