### ISSUE TITLE
Custom Query Rescorer

### ISSUE THREAD

**Issue by dmalipie** [elastic/elasticsearch-java#506]
### Description

**Java API client version**
8.5.3+

**Java version**
17

**Elasticsearch Version**
7.17.* - 8.*

**Problem description**

We have install a rescore plugin just like[ this one ](https://github.com/elastic/elasticsearch/blob/main/plugins/examples/rescore/src/main/java/org/elasticsearch/example/rescore/ExampleRescoreBuilder.java).

To use it we send a request like this:

```
[POST] /_search

{
    "query": {
         "match_all": {}
    },
    "rescore": {
        "example": {
            "factor": 2
        }
    }
} 
```
Unfortunately the Rescore model ([co.elastic.clients.elasticsearch.core.search.Rescore](https://github.com/elastic/elasticsearch-java/blob/main/java-client/src/main/java/co/elastic/clients/elasticsearch/core/search/Rescore.java)) allows only the use of a [RescoreQuery](https://github.com/elastic/elasticsearch-java/blob/main/java-client/src/main/java/co/elastic/clients/elasticsearch/core/search/RescoreQuery.java) model that will be serialized as:

```
{
    "rescore": {
        "query": {
            "rescore_query": {
                "match_phrase": {
                    "message": {
                        "query": "the quick brown",
                        "slop": 2
                    }
                }
            }
        }
    }
} 
```

Is it possible to add a new feature to define a Rescore model **with** a custom model to allow us to use a rescorer plugin ?

**Comment by edovac** [comment]
Can we have at least a triage of this issue?
