### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchMethodError: org.elasticsearch.client.RequestOptions$Builder.removeHeader(Ljava/lang/String;)Lorg/elasticsearch/client/RequestOptions$Builder;

### ISSUE THREAD

**Issue by xiaodizi** [elastic/elasticsearch-java#516]
### Java API client version

8.6.0

### Java version

1.8

### Elasticsearch Version

8.6.0

### Problem description

![image](https://user-images.githubusercontent.com/10411525/218618506-3dcea678-f85e-4dda-9313-1117c1c87080.png)
`/Library/Java/JavaVirtualMachines/jdk1.8.0_301.jdk/Contents/Home/bin/java -javaagent:/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar=56397:/Applications/IntelliJ IDEA.app/Contents/bin -Dfile.encoding=UTF-8 -classpath /Library/Java/JavaVirtualMachines/jdk1.8.0_301.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_301.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_301.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_301.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_301.jdk/Contents/Home/jre/lib/ext/jaccess.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_301.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_301.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_301.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_301.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_301.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_301.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_301.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_301.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_301.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_301.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_301.jdk/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_301.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_301.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_301.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_301.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_301.jdk/Contents/Home/jre/lib/rt.jar:/Users/lei.fu/java/mca/elastic-client/target/classes:/Users/lei.fu/java/localrepository/org/springframework/boot/spring-boot-starter-web/2.6.8/spring-boot-starter-web-2.6.8.jar:/Users/lei.fu/java/localrepository/org/springframework/boot/spring-boot-starter/2.6.8/spring-boot-starter-2.6.8.jar:/Users/lei.fu/java/localrepository/org/springframework/boot/spring-boot/2.6.8/spring-boot-2.6.8.jar:/Users/lei.fu/java/localrepository/org/springframework/boot/spring-boot-starter-logging/2.6.8/spring-boot-starter-logging-2.6.8.jar:/Users/lei.fu/java/localrepository/ch/qos/logback/logback-classic/1.2.11/logback-classic-1.2.11.jar:/Users/lei.fu/java/localrepository/ch/qos/logback/logback-core/1.2.11/logback-core-1.2.11.jar:/Users/lei.fu/java/localrepository/org/apache/logging/log4j/log4j-to-slf4j/2.17.2/log4j-to-slf4j-2.17.2.jar:/Users/lei.fu/java/localrepository/org/apache/logging/log4j/log4j-api/2.17.2/log4j-api-2.17.2.jar:/Users/lei.fu/java/localrepository/org/slf4j/jul-to-slf4j/1.7.36/jul-to-slf4j-1.7.36.jar:/Users/lei.fu/java/localrepository/jakarta/annotation/jakarta.annotation-api/1.3.5/jakarta.annotation-api-1.3.5.jar:/Users/lei.fu/java/localrepository/org/yaml/snakeyaml/1.29/snakeyaml-1.29.jar:/Users/lei.fu/java/localrepository/org/springframework/boot/spring-boot-starter-json/2.6.8/spring-boot-starter-json-2.6.8.jar:/Users/lei.fu/java/localrepository/com/fasterxml/jackson/datatype/jackson-datatype-jdk8/2.13.3/jackson-datatype-jdk8-2.13.3.jar:/Users/lei.fu/java/localrepository/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.13.3/jackson-datatype-jsr310-2.13.3.jar:/Users/lei.fu/java/localrepository/com/fasterxml/jackson/module/jackson-module-parameter-names/2.13.3/jackson-module-parameter-names-2.13.3.jar:/Users/lei.fu/java/localrepository/org/springframework/boot/spring-boot-starter-tomcat/2.6.8/spring-boot-starter-tomcat-2.6.8.jar:/Users/lei.fu/java/localrepository/org/apache/tomcat/embed/tomcat-embed-core/9.0.63/tomcat-embed-core-9.0.63.jar:/Users/lei.fu/java/localrepository/org/apache/tomcat/embed/tomcat-embed-el/9.0.63/tomcat-embed-el-9.0.63.jar:/Users/lei.fu/java/localrepository/org/apache/tomcat/embed/tomcat-embed-websocket/9.0.63/tomcat-embed-websocket-9.0.63.jar:/Users/lei.fu/java/localrepository/org/springframework/spring-web/5.3.20/spring-web-5.3.20.jar:/Users/lei.fu/java/localrepository/org/springframework/spring-beans/5.3.20/spring-beans-5.3.20.jar:/Users/lei.fu/java/localrepository/org/springframework/spring-webmvc/5.3.20/spring-webmvc-5.3.20.jar:/Users/lei.fu/java/localrepository/org/springframework/spring-aop/5.3.20/spring-aop-5.3.20.jar:/Users/lei.fu/java/localrepository/org/springframework/spring-context/5.3.20/spring-context-5.3.20.jar:/Users/lei.fu/java/localrepository/org/springframework/spring-expression/5.3.20/spring-expression-5.3.20.jar:/Users/lei.fu/java/localrepository/org/slf4j/slf4j-api/1.7.36/slf4j-api-1.7.36.jar:/Users/lei.fu/java/localrepository/org/springframework/spring-core/5.3.20/spring-core-5.3.20.jar:/Users/lei.fu/java/localrepository/org/springframework/spring-jcl/5.3.20/spring-jcl-5.3.20.jar:/Users/lei.fu/java/localrepository/com/alibaba/fastjson2/fastjson2/2.0.23/fastjson2-2.0.23.jar:/Users/lei.fu/java/localrepository/co/elastic/clients/elasticsearch-java/8.6.0/elasticsearch-java-8.6.0.jar:/Users/lei.fu/java/localrepository/org/elasticsearch/client/elasticsearch-rest-client/7.15.2/elasticsearch-rest-client-7.15.2.jar:/Users/lei.fu/java/localrepository/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar:/Users/lei.fu/java/localrepository/org/apache/httpcomponents/httpcore/4.4.15/httpcore-4.4.15.jar:/Users/lei.fu/java/localrepository/org/apache/httpcomponents/httpasyncclient/4.1.5/httpasyncclient-4.1.5.jar:/Users/lei.fu/java/localrepository/org/apache/httpcomponents/httpcore-nio/4.4.15/httpcore-nio-4.4.15.jar:/Users/lei.fu/java/localrepository/commons-codec/commons-codec/1.15/commons-codec-1.15.jar:/Users/lei.fu/java/localrepository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar:/Users/lei.fu/java/localrepository/org/eclipse/parsson/parsson/1.0.0/parsson-1.0.0.jar:/Users/lei.fu/java/localrepository/com/fasterxml/jackson/core/jackson-databind/2.12.3/jackson-databind-2.12.3.jar:/Users/lei.fu/java/localrepository/com/fasterxml/jackson/core/jackson-annotations/2.13.3/jackson-annotations-2.13.3.jar:/Users/lei.fu/java/localrepository/com/fasterxml/jackson/core/jackson-core/2.13.3/jackson-core-2.13.3.jar:/Users/lei.fu/java/localrepository/jakarta/json/jakarta.json-api/2.0.1/jakarta.json-api-2.0.1.jar:/Users/lei.fu/java/localrepository/mysql/mysql-connector-java/8.0.29/mysql-connector-java-8.0.29.jar:/Users/lei.fu/java/localrepository/com/baomidou/mybatis-plus-boot-starter/3.5.2/mybatis-plus-boot-starter-3.5.2.jar:/Users/lei.fu/java/localrepository/com/baomidou/mybatis-plus/3.5.2/mybatis-plus-3.5.2.jar:/Users/lei.fu/java/localrepository/com/baomidou/mybatis-plus-extension/3.5.2/mybatis-plus-extension-3.5.2.jar:/Users/lei.fu/java/localrepository/com/baomidou/mybatis-plus-core/3.5.2/mybatis-plus-core-3.5.2.jar:/Users/lei.fu/java/localrepository/com/baomidou/mybatis-plus-annotation/3.5.2/mybatis-plus-annotation-3.5.2.jar:/Users/lei.fu/java/localrepository/com/github/jsqlparser/jsqlparser/4.4/jsqlparser-4.4.jar:/Users/lei.fu/java/localrepository/org/mybatis/mybatis/3.5.10/mybatis-3.5.10.jar:/Users/lei.fu/java/localrepository/org/mybatis/mybatis-spring/2.0.7/mybatis-spring-2.0.7.jar:/Users/lei.fu/java/localrepository/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.6.21/kotlin-stdlib-jdk8-1.6.21.jar:/Users/lei.fu/java/localrepository/org/jetbrains/kotlin/kotlin-stdlib/1.6.21/kotlin-stdlib-1.6.21.jar:/Users/lei.fu/java/localrepository/org/jetbrains/kotlin/kotlin-stdlib-common/1.6.21/kotlin-stdlib-common-1.6.21.jar:/Users/lei.fu/java/localrepository/org/jetbrains/annotations/13.0/annotations-13.0.jar:/Users/lei.fu/java/localrepository/org/jetbrains/kotlin/kotlin-stdlib-jdk7/1.6.21/kotlin-stdlib-jdk7-1.6.21.jar:/Users/lei.fu/java/localrepository/org/springframework/boot/spring-boot-autoconfigure/2.6.8/spring-boot-autoconfigure-2.6.8.jar:/Users/lei.fu/java/localrepository/org/springframework/boot/spring-boot-starter-jdbc/2.6.8/spring-boot-starter-jdbc-2.6.8.jar:/Users/lei.fu/java/localrepository/com/zaxxer/HikariCP/4.0.3/HikariCP-4.0.3.jar:/Users/lei.fu/java/localrepository/org/springframework/spring-jdbc/5.3.20/spring-jdbc-5.3.20.jar:/Users/lei.fu/java/localrepository/org/springframework/spring-tx/5.3.20/spring-tx-5.3.20.jar com.elastic.client.client.ESClientDemo
Exception in thread "main" java.lang.NoSuchMethodError: org.elasticsearch.client.RequestOptions$Builder.removeHeader(Ljava/lang/String;)Lorg/elasticsearch/client/RequestOptions$Builder;
	at co.elastic.clients.transport.rest_client.RestClientOptions.addBuiltinHeaders(RestClientOptions.java:170)
	at co.elastic.clients.transport.rest_client.RestClientOptions.<init>(RestClientOptions.java:64)
	at co.elastic.clients.transport.rest_client.RestClientOptions.initialOptions(RestClientOptions.java:166)
	at co.elastic.clients.transport.rest_client.RestClientTransport.<init>(RestClientTransport.java:104)
	at co.elastic.clients.transport.rest_client.RestClientTransport.<init>(RestClientTransport.java:108)
	at com.elastic.client.client.ESClient.<clinit>(ESClient.java:22)
	at com.elastic.client.client.ESClientDemo.main(ESClientDemo.java:22)
`

Why does this happen?

**Comment by xiaodizi** [comment]
My pom file 
`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.6.8</version>
        <relativePath/> 
    </parent>
    <groupId>com.elastic</groupId>
    <artifactId>elastic-client</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>elastic-client</name>
    <description>elastic-client</description>

    <developers>
        <developer>
            <name>lei.fu</name>
            <email>305297641@qq.com</email>
        </developer>
    </developers>

    <properties>
        <java.version>1.8</java.version>
    </properties>

    <repositories>
        <repository>
            <id>nexus-aliyun</id>
            <name>Nexus aliyun</name>
            <url>https://maven.aliyun.com/repository/public</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>com.alibaba.fastjson2</groupId>
            <artifactId>fastjson2</artifactId>
            <version>2.0.23</version>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.26</version>
            <scope>provided</scope>
        </dependency>

        
        <dependency>
            <groupId>co.elastic.clients</groupId>
            <artifactId>elasticsearch-java</artifactId>
            <version>8.6.0</version>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.12.3</version>
        </dependency>
        <dependency>
            <groupId>jakarta.json</groupId>
            <artifactId>jakarta.json-api</artifactId>
            <version>2.0.1</version>
        </dependency>
        

        




        

        
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.5.2</version>
        </dependency>
        




    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                    <encoding>UTF-8</encoding>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>
`

**Comment by xiaodizi** [comment]
I tried the java client using 8.1.3 to connect to the 8.6.0 cluster

**Comment by swallez** [comment]
Your classpath indicates `elasticsearch-rest-client-7.15.2.jar`. The method `RequestOptions$Builder.removeHeader` was added in version 7.16.

Something in your build environment is overriding the version 8.6.0 which is pulled by `elasticsearch-java`. Try adding `elasticsearch-rest-client` as an explicit dependency.

```
    <dependency>
      <groupId>org.elasticsearch.client</groupId>
      <artifactId>elasticsearch-rest-client</artifactId>
      <version>8.6.0</version>
    </dependency>
```

**Comment by xiaodizi** [comment]
> Your classpath indicates `elasticsearch-rest-client-7.15.2.jar`. The method `RequestOptions$Builder.removeHeader` was added in version 7.16.
> 
> Something in your build environment is overriding the version 8.6.0 which is pulled by `elasticsearch-java`. Try adding `elasticsearch-rest-client` as an explicit dependency.
> 
> ```
>     <dependency>
>       <groupId>org.elasticsearch.client</groupId>
>       <artifactId>elasticsearch-rest-client</artifactId>
>       <version>8.6.0</version>
>     </dependency>
> ```

thanks
