### ISSUE TITLE
Elasticsearch API client 8.6.2 is not compatible with Elasticsearch rest client 7.15.2

### ISSUE THREAD

**Issue by amitmbm** [elastic/elasticsearch-java#521]
### Java API client version

8.6.2

### Java version

17

### Elasticsearch Version

8.6.2

### Problem description

I am upgrading my Java API client from 8.3.3 to 8.6.2 and notice that my Elasticsearch client is not getting initialised and throwing following error.

```
Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    co.elastic.clients.transport.rest_client.RestClientOptions.addBuiltinHeaders(RestClientOptions.java:170)

The following method did not exist:

    'org.elasticsearch.client.RequestOptions$Builder org.elasticsearch.client.RequestOptions$Builder.removeHeader(java.lang.String)'

The calling method's class, co.elastic.clients.transport.rest_client.RestClientOptions, was loaded from the following location:

    jar:file:/Users/amit/.m2/repository/co/elastic/clients/elasticsearch-java/8.6.2/elasticsearch-java-8.6.2.jar!/co/elastic/clients/transport/rest_client/RestClientOptions.class

The called method's class, org.elasticsearch.client.RequestOptions$Builder, is available from the following locations:

    jar:file:/Users/amit/.m2/repository/org/elasticsearch/client/elasticsearch-rest-client/7.15.2/elasticsearch-rest-client-7.15.2.jar!/org/elasticsearch/client/RequestOptions$Builder.class

The called method's class hierarchy was loaded from the following locations:

    org.elasticsearch.client.RequestOptions.Builder: file:/Users/amit/.m2/repository/org/elasticsearch/client/elasticsearch-rest-client/7.15.2/elasticsearch-rest-client-7.15.2.jar


Action:

Correct the classpath of your application so that it contains compatible versions of the classes co.elastic.clients.transport.rest_client.RestClientOptions and org.elasticsearch.client.RequestOptions$Builder 
```

I was suprised to see   *org.elasticsearch.client.RequestOptions.Builder: file:/Users/amit/.m2/repository/org/elasticsearch/client/elasticsearch-rest-client/7.15.2/elasticsearch-rest-client-7.15.2.jar
* in the error message but found its getting downloaded by API client as shown

```
[INFO] +- co.elastic.clients:elasticsearch-java:jar:8.6.2:compile
[INFO] |  +- org.elasticsearch.client:elasticsearch-rest-client:jar:7.15.2:compile
[INFO] |  |  +- org.apache.httpcomponents:httpclient:jar:4.5.13:compile
[INFO] |  |  +- org.apache.httpcomponents:httpcore:jar:4.4.15:compile
[INFO] |  |  +- org.apache.httpcomponents:httpasyncclient:jar:4.1.5:compile
[INFO] |  |  +- org.apache.httpcomponents:httpcore-nio:jar:4.4.15:compile
[INFO] |  |  \- commons-codec:commons-codec:jar:1.15:compile
[INFO] |  +- com.google.code.findbugs:jsr305:jar:3.0.2:compile
```

Now when I switched back to again 8.3.3 its(rest client) still getting downloaded with same version but its working fine. 

P.S I tried it with API client 8.5 also and same issue persist there as well.

**Comment by amitmbm** [comment]
@swallez can you please look into this issue

**Comment by swallez** [comment]
`elasticsearch-java` version 8.6.2 has a dependency on the same version of `elasticsearch-rest-client`: see the [POM file on Maven Central](https://central.sonatype.com/artifact/co.elastic.clients/elasticsearch-java/8.6.2).

There must be something in your build system that sets `elasticsearch-rest-client` to version 7.15.2. Try adding a top-level dependency to the correct version.

**Comment by bhavyaidr** [comment]
I also faced a similar issue when upgrading the Elasticsearch API client from 8.3 to 8.6.2.

To resolve this issue, you can try excluding the conflicting transitive dependency from your project's dependencies. You can do this by adding an exclusions element to the dependency in your POM file, like this:

```
<dependency>
	<groupId>co.elastic.clients</groupId>
	<artifactId>elasticsearch-java</artifactId>
	<version>8.1.3</version>
	<version>8.6.2</version>
	<!-- excluding the conflicting transitive dependency from the project's dependencies -->
	<exclusions>
		<exclusion>
			<groupId>org.elasticsearch.client</groupId>
			<artifactId>elasticsearch-rest-client</artifactId>
		</exclusion>
	</exclusions>
</dependency>
```

And, then explicitly add the elasticsearch-rest-client library as a direct dependency in your POM file

```
<dependency>
	<groupId>org.elasticsearch.client</groupId>
	<artifactId>elasticsearch-rest-client</artifactId>
	<version>8.6.2</version>
</dependency>
```
