### ISSUE TITLE
MoreLikeThisQuery should not allow `per_field_analyzer` outside `like` parameter

### ISSUE THREAD

**Issue by fabriziofortino** [elastic/elasticsearch-java#533]
### Java API client version

7.17.7

### Java version

openjdk version "19" 2022-09-20

### Elasticsearch Version

7.17.7

### Problem description

The following code:

``` java
MoreLikeThisQuery.Builder mlt = new MoreLikeThisQuery.Builder();
mlt.perFieldAnalyzer("my_field", "keyword")));
mlt.build()
```

is currently allowed by the client and produces a malformed query. 

`per_field_analyzer` should be allowed in the `like` option only.

**Comment by l-trotta** [comment]
Hello, thank you for reporting this! You are correct, `per_field_analyzer` should not be present in the more like this query builder, this is an issue in the [API specification](https://github.com/elastic/elasticsearch-specification) used to produce the Java code, once fixed we will regenerate the code to solve this. Thanks again!
