### ISSUE TITLE
Missing required property TaskStatus.batches when calling tasks().list()

### ISSUE THREAD

**Issue by LBoraz** [elastic/elasticsearch-java#536]
### Java API client version

8.6.2

### Java version

19

### Elasticsearch Version

8.4.1

### Problem description

The following code will return an error because the client performs a null check on a property that is not returned in the response:

```java
Function<ListRequest.Builder, ObjectBuilder<ListRequest>> fn =
                b -> b.detailed(true).groupBy(GroupBy.Nodes);
ListResponse listResponse = client.tasks().list(fn);
```

Error returned

```
co.elastic.clients.json.JsonpMappingException: Error deserializing co.elastic.clients.elasticsearch.tasks.TaskInfo: co.elastic.clients.util.MissingRequiredPropertyException: Missing required property 'TaskStatus.batches' (JSON path: nodes['wg0411ZYS-yDdTD0KZShDQ'].tasks['wg0411ZYS-yDdTD0KZShDQ:117270296'].status) (line no=1, column no=2483, offset=-1)
```

Using 
```java
ApiTypeHelper.DANGEROUS_disableRequiredPropertiesCheck(true); 
```

as recommended in the [docs](https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/current/missing-required-property.html) leads to another error:

```
co.elastic.clients.json.JsonpMappingException: Error deserializing co.elastic.clients.elasticsearch.tasks.TaskInfo: java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because the return value of "co.elastic.clients.util.ApiTypeHelper.requireNonNull(Object, Object, String)" is null (JSON path: nodes['wg0411ZYS-yDdTD0KZShDQ'].tasks['wg0411ZYS-yDdTD0KZShDQ:117270296'].status) (line no=1, column no=2818, offset=-1)
```

**Comment by l-trotta** [comment]
Hello, thank you for the report. This was an issue with the [API specification](https://github.com/elastic/elasticsearch-specification) used to produce the Java code, and it was fixed with this [PR](https://github.com/elastic/elasticsearch-specification/pull/2250).
