### ISSUE TITLE
Missing X-Elastic-Product header

### ISSUE THREAD

**Issue by mindscratch** [elastic/elasticsearch-java#54]
Since upgrading from the 7.15.x client to the 7.16.0 client I am getting a `TransportException`:

```
co.elastic.clients.transport.TransportException: [es/search] Missing [X-Elastic-Product] header. Please check that you are connecting to an Elasticsearch instance, and that any networking filters are preserving that header.
```

**Comment by swallez** [comment]
What version of Elasticsearch are you using? The Java client requires Elasticsearch version 7.14 as a minimum.

See also our [compatibility guarantees](https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/current/introduction.html#_compatibility).

**Comment by swallez** [comment]
The 7.16 version has additional logic to be compatible with Elasticsearch 8.0 that will have a "7.0 compatible mode" to ease the transition to this new major version.

The server-side part of this migration logic was added to Elasticsearch 7.14, and this is why the new Java client requires Elasticsearch 7.14 or more. We'll update the docs with information about this absolute minimal version requirement.

**Comment by mindscratch** [comment]
Thanks, I'll switch to the rest high-level client while we're still on the older ES.
