### ISSUE TITLE
[Feature Request] Micrometer integration

### ISSUE THREAD

**Issue by patpatpat123** [elastic/elasticsearch-java#541]
### Description

Hello Elastic team,

This is my first writing in this repo although I am using the client on a regular basis. 
If not anything, thank you for this project.

I wanted to start this feature request enhancement request, asking if it is possible to add micrometer to this project.

Metrics and tracing are vital component of any production level component.
Therefore, in each of our projects, any integration we have with ElasticSearch using this elasticsearch-java client, we need to manually add tracing and metrics.

For instance, when we have a read or write operation with elastic, using the blocking or async api, one has to manually create metrics. (number of write, time taken, count of errors, etc), alongside traces correlating the application calling the read write (parent) to elasticsearch-java client (child trace).

Apologies to repeat myself, but since metrics and tracing are vital component of production level applications, would it be possible to have built in to this project:

- **metrics** for read write operations with ElasticSearch
- **traces** for read write operations with ElasticSearch

Thank you

**Comment by swallez** [comment]
This has already been discussed and ultimately rejected in https://github.com/elastic/elasticsearch/issues/93591#issuecomment-1473973524

**Comment by swallez** [comment]
@patpatpat123 PR #588 adds an instrumentation API with a default implementation based on OpenTelemetry. Adding an implementation based on Micrometer should be fairly straightforward.
