### ISSUE TITLE
Significant Text aggregation missing regex include method

### ISSUE THREAD

**Issue by karolp-vtool** [elastic/elasticsearch-java#544]
### Java API client version

elasticsearch-java:8.7.0
elasticsearch-java:8.9.2

### Java version
JDK 17

### Elasticsearch Version

8.7
8.9.2

### Problem description

Hello,
by documentation of SignificantTextAggregation, it should support regex aggregation for "include" field. Currently it supports only an array of strings.
List<String> include should be changed to TermsInclude include;
This is similar issue to: https://github.com/elastic/elasticsearch-java/issues/85

Best regards,
Karol

**Comment by karolp-vtool** [comment]
Will someone pick up this bug? 
Or should I log the issue somewhere else?

**Comment by karolp-vtool** [comment]
Updated the ES version and Java API client. Same problem exists on 8.7.

**Comment by karolp-vtool** [comment]
Same problem exists in 8.9.2.

**Comment by pquentin** [comment]
https://github.com/elastic/elasticsearch-specification/issues/2275 is now fixed
