### ISSUE TITLE
Add support for now knn search in _search endpoint

### ISSUE THREAD

**Issue by adrian-arapiles** [elastic/elasticsearch-java#556]
### Description

Right now, the client make a knn request vs `_knn_search` endpoint instead of using new field in `_search`endpoint.
Could be nice if add support for that in `_search` endpoint to be more useful.
https://www.elastic.co/guide/en/elasticsearch/reference/current/knn-search.html#approximate-knn

Thanks.

**Comment by swallez** [comment]
It is available in the Java client since version 8.6.0, which when it was moved in Elasticsearch server from `_knn_search` to `_search`.

See https://artifacts.elastic.co/javadoc/co/elastic/clients/elasticsearch-java/8.6.0/co/elastic/clients/elasticsearch/core/SearchRequest.html#knn()
