### ISSUE TITLE
SimulateIndexTemplateResponse is empty

### ISSUE THREAD

**Issue by ztyzbb** [elastic/elasticsearch-java#572]
### Description

The object SimulateIndexTemplateResponse is empty, which isn't consist with doc.
[Simulate multi-component templates](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/simulate-multi-component-templates.html)
Hope can backport to 7.17, thank you!

**Comment by l-trotta** [comment]
Hello, thank you for reporting this! Yes of course it shouldn't be empty ^^" it's definitely a bug, we'll investigate this.
