### ISSUE TITLE
the elastic java client 8.7.0 requires java 17 instead of java 8

### ISSUE THREAD

**Issue by inrix-angel** [elastic/elasticsearch-java#618]
### Java API client version

8.7.0

### Java version

8

### Elasticsearch Version

OpenSearch 2.5.0

### Problem description

When upgrading to the 8.7.0 version of the Elastic java client, I'm seeing errors such as this one:

[ERROR]   bad class file: /Users/todorov/.m2/repository/org/elasticsearch/elasticsearch/8.7.0/elasticsearch-8.7.0.jar(org/elasticsearch/index/query/BoolQueryBuilder.class)
[ERROR]     class file has wrong version 61.0, should be 52.0

I'm using Java 8 and in the Elastic docs, it is clearly stated that:

Requirements:

Java 8 or later.

https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/current/installation.html

Thanks.

**Comment by pdl01** [comment]
running into the same with other earlier 8.x api versions. 

Is there any priority on this issue since the documentation does say this is compatible with java 1.8.

**Comment by slawekjaranowski** [comment]
I use `8.13.0` with JDK 1.8 - so looks like issue was resolved for newer versions
