### ISSUE TITLE
calling client.nodes().stats() results in an exception

### ISSUE THREAD

**Issue by inrix-angel** [elastic/elasticsearch-java#619]
### Java API client version

7.17.11

### Java version

8

### Elasticsearch Version

7.10

### Problem description

       `     NodesStatsResponse result = client.nodes().stats();`

(where client is an instance of an ElasticSearchClient)

result:

`jakarta.json.stream.JsonParsingException: Jackson exception: Numeric value (628037356913) out of range of int (-2147483648 - 2147483647)
 at [Source: (org.apache.http.nio.entity.ContentInputStream); line: 1, column: 347]`

**Comment by INRIX-Angel-Todorov** [comment]
Note i have 1763 active shards, 887 active primary shards, around 400 indices totalling 1,110,615,971 searchable documents . they take around 2 TB. It seems there's clearly a flaw in the sense that there are some assumptions made about the max sizes in the cluster /node stats endpoint
