### ISSUE TITLE
Could you supply a detail document about it like java high level client?

### ISSUE THREAD

**Issue by Alexhuihui** [elastic/elasticsearch-java#62]
I think the api document of  java high level client is easy to understand. But the java api client is simple and missing a lot of detail about how to use it to communicate with the elastic. Thanks.

**Comment by swallez** [comment]
Thanks for your feedback @Alexhuihui. The Java API client is still new and the docs will improve. Can you provide more information on the kind of documentation you would like to see, or links to the corresponding docs in the Java High Level Client?

**Comment by bybike** [comment]
@swallez  hi, Java High Level Client link is here:
https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/index.html
Like this type of doc is easy to read and learn how to code with client

**Comment by angles-n-daemons** [comment]
I think concrete code examples detailing usage would be super helpful. I tried using the source of the Java API client to construct requests, and got a lot more confused than I thought I would.

I think including code examples for specific use cases (update doc, get doc, query index, etc) like the high level rest client would drive much faster adoption of the Java API client.
