### ISSUE TITLE
Maven Artifacts missing in Maven-Central

### ISSUE THREAD

**Issue by fabian-froehlich** [elastic/elasticsearch-java#641]
### Java API client version

8.9.0

### Java version

17

### Elasticsearch Version

8.9.0

### Problem description

The Maven-Dependency for 8.9.0 seems to be missing in:
https://repo1.maven.org/maven2/co/elastic/clients/elasticsearch-java/

**Comment by thaarbach** [comment]
Can confirm that 

![image](https://github.com/elastic/elasticsearch-java/assets/4933467/b92dad80-a7fe-4210-8275-b0e6b539e5e2)

**Comment by xeraa** [comment]
Thanks for reporting! Should be available now: https://central.sonatype.com/artifact/co.elastic.clients/elasticsearch-java/8.9.0/versions :)
