### ISSUE TITLE
The document have a wrong description

### ISSUE THREAD

**Issue by robin536180** [elastic/elasticsearch-java#646]
### Java API client version

8.9.0

### Java version

8

### Elasticsearch Version

7.17

### Problem description

![image](https://github.com/elastic/elasticsearch-java/assets/8565176/b608b0e5-c1b9-414d-8cc6-425f102e3ff4)
Here should be delete index, but the code is to create, I think this should be a little mistake.

**Comment by l-trotta** [comment]
Closing this as it has been fixed, thank you!
