### ISSUE TITLE
Missing required property 'IndexResponse.primaryTerm'

### ISSUE THREAD

**Issue by lorenzomalla** [elastic/elasticsearch-java#657]
### Java API client version

8.5.3

### Java version

17

### Elasticsearch Version

8.9

### Problem description

Hi,
I'm try to create a new document with ElasticsearchClient with IndexRequest and receive `'co.elastic.clients.util.MissingRequiredPropertyException: Missing required property 'IndexResponse.primaryTerm'`, if I call the API of ES from postman work it.
I try to set `ApiTypeHelper.DANGEROUS_disableRequiredPropertiesCheck(true);` but not work.

**Comment by l-trotta** [comment]
Hello! This was recently solved in [#776](https://github.com/elastic/elasticsearch-java/pull/776), thanks for reporting it.
