### ISSUE TITLE
Geodistance query is missing "ignore unmapped"

### ISSUE THREAD

**Issue by rgevaerd** [elastic/elasticsearch-java#659]
### Java API client version

8.9

### Java version

17

### Elasticsearch Version

8.9

### Problem description

The ignore unmapped (https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-geo-distance-query.html#_ignore_unmapped_2) is missing from the geo distance query in the Elasticsearch Java API.

In the old (resthighlevel) client it was present: https://artifacts.elastic.co/javadoc/org/elasticsearch/elasticsearch/7.17.12/org/elasticsearch/index/query/GeoDistanceQueryBuilder.html#ignoreUnmapped(boolean)

**Comment by l-trotta** [comment]
This was a specification bug fixed with https://github.com/elastic/elasticsearch-specification/pull/2391, closing this, thanks for the report!
