### ISSUE TITLE
null value in SearchResponse.hits.hits.sort causes parsing failure

### ISSUE THREAD

**Issue by swallez** [elastic/elasticsearch-java#66]
From https://discuss.elastic.co/t/failure-with-sorts-and-new-co-elastic-clients-elasticsearch-java-client/291511/8

When a request is sorted on fields that may have `null` values, the responses's `hits.hits.sort` array will contain `null` values that cause a parsing failure as arrays generally don't accept `null` values in the API spec.

This is related to https://github.com/elastic/elasticsearch-specification/issues/1109 and will be solved once `sort` is considered as an opaque JSON blob.

/cc @ilgrosso

**Comment by jetpack1116** [comment]
Hi @swallez 

I encounter this problem in 7.17.6, it seems its not fix yet?
Please see https://discuss.elastic.co/t/new-elasticsearch-client-search-response-cannot-be-serialized-because-of-null-value-on-sort-fields/315326/6

**Comment by imjuoy** [comment]
Is there an update on this? Is this fixed ?
