### ISSUE TITLE
Wrapper query implementation missing

### ISSUE THREAD

**Issue by sothawo** [elastic/elasticsearch-java#67]
Client version 7.16.1:

It seems that the `co.elastic.clients.elasticsearch._types.query_dsl.Query` is missing the _wrapper_ query type (https://www.elastic.co/guide/en/elasticsearch/reference/7.16/query-dsl-wrapper-query.html).

**Comment by swallez** [comment]
It was indeed missing in the API specification and has been added in https://github.com/elastic/elasticsearch-specification/pull/1132

Out of curiosity, what are your use cases for this query type?

**Comment by sothawo** [comment]
For Spring Data Elasticsearch this is pretty important. It's the way a user can add custom queries when using Spring Data repositories. The user can add a `@Query()` annotation to a repository method (https://docs.spring.io/spring-data/elasticsearch/docs/current/reference/html/#elasticsearch.query-methods.at-query).

When such a method is called we do a parameter replacement in the query argument of the annotation and then send this as the query part of a search request.

**Comment by sothawo** [comment]
Is this available in a snapshot yet? I check 7.16.2-SNAPSHOT but it's not in that yet.

**Comment by swallez** [comment]
Sorry for the late answer and resolution. This has been added in [#71c2c17e25](https://github.com/elastic/elasticsearch-java/blob/71c2c17e253e8dcabeda615a859880026cae1697/java-client/src/main/java/co/elastic/clients/elasticsearch/_types/query_dsl/WrapperQuery.java) and is available in snapshots.

**Comment by sothawo** [comment]
sorry to ask again, in which snapshot version? Didn't find it in 7.16.4-SNAPSHOT and not in 7.17.0-SNAPSHOT

**Comment by swallez** [comment]
Sorry, my bad, I pushed these changes today, so they will be available tomorrow morning (snapshots are usually built around 5am UTC).

You can see the builds at https://artifacts-api.elastic.co/v1/versions/7.17-SNAPSHOT/ - the most recent snapshot is described at `versions.builds[0].projects.elasticsearch-java`

**Comment by sothawo** [comment]
Somehow I cannot seem to get a snapshot version from https://snapshots.elastic.co/maven/ that contains this fix. I have cleared my ~/.m2/repository directory for the client and re-downloaded 7.17-SNAPSHOT, but these changes are not in.  The manifest from the jar shows:

```
Manifest-Version: 1.0
Implementation-Title: Elasticsearch Java client
Implementation-Vendor: Elastic
Implementation-URL: https://github.com/elastic/elasticsearch-java/
Build-Date: 2022-01-23T00:16:56.465215031Z
X-Git-Revision: f09b12c03fdb2b6f2e8378a26dc22a01f879c54b
X-Git-Commit-Time: 2022-01-05T17:50:32Z
```

I managed to built my own version by forking/updating the 7.17 branch, setting the correct value in _config/version.txt_ and running 
```
gradle build publishToMavenLocal
```

**Comment by swallez** [comment]
The snapshot has not been published today, as can be seen on https://artifacts-api.elastic.co/v1/versions/7.17-SNAPSHOT/

Snapshots are the result of building the entire suite of Elastic products once a day and publish them to the snapshot repository all at once, or none at all if one of the individual product build fails.

Build failures don't happen often, but when they do this means no snapshot is published that day. And of course fixing it is top priority for the corresponding team. Hopefully tomorrow we well have a fresh snapshot!

**Comment by swallez** [comment]
@sothawo a new snapshot is available that contains the `wrapper` query!

**Comment by sothawo** [comment]
got it in 7.17.0-SNAPSHOT, but not in 7.16.4-SNAPSHOT, but that's ok for me
