### ISSUE TITLE
Java API Doc Typo

### ISSUE THREAD

**Issue by Fulwing** [elastic/elasticsearch-java#687]
### Java API client version

8.10

### Java version

17

### Elasticsearch Version

8.10

### Problem description

for the [delete index](https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/current/getting-started-java.html#_deleting_an_index), I think there is a typo, it should be delete not create.

**Comment by zeze1004** [comment]
I have reviewed the issue and submitted a PR!

**Comment by l-trotta** [comment]
closed as it has already been fixed and will show the correct name from the next version, thank you!
