### ISSUE TITLE
Dependency Error !

### ISSUE THREAD

**Issue by xiattong** [elastic/elasticsearch-java#715]
### Java API client version

8.11.1

### Java version

jdk-20

### Elasticsearch Version

8.11.1

### Problem description

When I depend on elasticsearch-java:8.11.1, it depend on elasticsearch-rest-client:7.12.1, causing my program to start incorrectly! I had to exclude elasticsearch-rest-client:7.12.1 in elasticsearch-java:8.11.1 and add elasticsearch-rest-client:8.11.1

**Comment by swallez** [comment]
There must be another dependency that pull version 7.12.1 as elasticsearch-java:8.11.1 depends on elasticsearch-rest-client:8.11.1.
See dependencies at https://search.maven.org/artifact/co.elastic.clients/elasticsearch-java/8.11.1/jar
