### ISSUE TITLE
co.elastic.clients.transport.VERSION is not up to date

### ISSUE THREAD

**Issue by fabriziofortino** [elastic/elasticsearch-java#717]
### Java API client version

8.11.1

### Java version

17

### Elasticsearch Version

8.11.1

### Problem description

`co.elastic.clients.transport.VERSION` returns `8.11.0` on both elasticsearch-java 8.11.1 and 8.11.2. Shouldn't the version be aligned with the client version?

**Comment by sothawo** [comment]
Now we have 8.12.0, but it still returns 8.11.0
