### ISSUE TITLE
8.11.3 not on Maven central

### ISSUE THREAD

**Issue by ilgrosso** [elastic/elasticsearch-java#719]
### Elasticsearch Version

8.11.3

### Java Version

openjdk version "11.0.21" 2023-10-17 LTS

### OS Version

Linux betulla 6.2.0-39-generic elastic/elasticsearch#40~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov 16 10:53:04 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Problem Description

Latest 8.11.3 is not available on Maven central

### Steps to Reproduce

https://central.sonatype.com/artifact/co.elastic.clients/elasticsearch-java/versions does not show 8.11.3

**Comment by ltmleo** [comment]
[maven.org](https://repo1.maven.org/maven2/co/elastic/clients/elasticsearch-java/) also does not have 8.11.3 version:
https://repo1.maven.org/maven2/co/elastic/clients/elasticsearch-java/8.11.3/ -> 404 not found

**Comment by apupier** [comment]
It is now visible everywhere:
![image](https://github.com/elastic/elasticsearch-java/assets/1105127/ee9cf18b-0c0b-45ed-bd0e-6f5fe33f3053)

![image](https://github.com/elastic/elasticsearch-java/assets/1105127/8cb91f76-156e-4e34-8837-56e05ac89182)
