### ISSUE TITLE
GetIndexTemplate call fails with MissingRequiredPropertyException: Missing required property 'IndexTemplate.composedOf'

### ISSUE THREAD

**Issue by sothawo** [elastic/elasticsearch-java#729]
### Java API client version

8.12.0

### Java version

17.0.10

### Elasticsearch Version

8.12.0

### Problem description

Since version 8.12.0 the `composedOf` property of the IndexTemplate is not nullable anymore (https://github.com/elastic/elasticsearch-specification/blob/main/specification/indices/_types/IndexTemplate.ts#L40)

It is not possible now to read an index template that is not composed of other components. But this is still a valid case (see https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-put-template.html#put-index-template-api-request-body, composedOf is optional).

Using the try `ApiTypeHelper.DANGEROUS_disableRequiredPropertiesCheck(true))` workaround does not help, because the json deserializer tries to deserialize null into a list when adding this.

8.11.4 did not have this problem.

**Comment by fabian-froehlich** [comment]
Not sure weather this is a problem of the client, or the serverside. Posted this issue on the main project: https://github.com/elastic/elasticsearch/issues/104627

**Comment by sothawo** [comment]
> The quoted API is for PUT-Requests and describes an optional parameter, that you can put in your body.

Yes, I saw that, but there is no documentation what `get` returns, so I linked that. Supposing that I can get back what I put in. I noticed because the build of spring-data-elasticsearch failed after the upgrade. Thanks for adding this bug to the main project.

**Comment by marcgise** [comment]
Does it still happens in 8.12.1 or do you find any workaround?

**Comment by sothawo** [comment]
The PR in the Elasticsearch project that restores the previous behaviour (https://github.com/elastic/elasticsearch/pull/105315) is tagged with v8.13. It seems we have to wait some time then.

**Comment by sothawo** [comment]
![image](https://github.com/elastic/elasticsearch-java/assets/8456476/d0fc3fe4-f202-4785-af1b-edee11117a3a)
wow, now planned for 8.14?

**Comment by marcgise** [comment]
I downgraded my system to 8.11.4 due to this bug... :(

**Comment by sothawo** [comment]
yeah, in 2 days there should be the milestone-1 release of Spring Data Elasticsearch 2024.0.0-M1 and I need to stay on 8.11 as well. Only waiting for the Spring Boot team to ask me to bump up to 8.12 before boot 3.3.0-M2 is released and then telling them "no".

**Comment by frank-montyne** [comment]
I have the same problem. Is very basic functionality, why does this have to take so long? Anyone aware of a workaround except for staying on 8.11.4?

**Comment by sothawo** [comment]
Seems to be fixed in 8.12.2, so this issue can be closed
