### ISSUE TITLE
SearchResponse.documents() return an empty list

### ISSUE THREAD

**Issue by AneonCode** [elastic/elasticsearch-java#75]
- ES version: 7.16.2
- elasticsearch-java version: 7.16.2

Trying to use `client.search().documents()`, but I got an empty list:

```java
List<Major> majorList = this.elasticsearchClient.search(s ->
                                                    s.size(RECOMMEND_SIZE)
                                                        .index("major")
                                                        .query(q ->
                                                            q.bool(bl ->
                                                                bl.must(mst ->
                                                                    mst.match(match ->
                                                                        match.field("name")
                                                                                .query(qr -> qr.stringValue(name))
                                                                                .fuzziness("AUTO"))))),
                                                Major.class).documents();
```

 The `majorList` is empty. But when I use the `client.search().hits().hits()` the result contains what I need.

 Am I using it the wrong way？

**Comment by swallez** [comment]
Thanks for the feedback. Indeed, this is a bug in the API specification used to generate the client. This [has been fixed recently](https://github.com/elastic/elasticsearch-specification/pull/1068) and the top-level `documents()` will be removed in the next minor release.

As you rightly point out, the results are available in `.hits().hits()`.

**Comment by AneonCode** [comment]
> Thanks for the feedback. Indeed, this is a bug in the API specification used to generate the client. This [has been fixed recently](https://github.com/elastic/elasticsearch-specification/pull/1068) and the top-level `documents()` will be removed in the next minor release.
> 
> As you rightly point out, the results are available in `.hits().hits()`.

Thanks very much. I will use `.hits().hits()` then in my project.
