### ISSUE TITLE
Inconsistent type for IndexTemplate priority

### ISSUE THREAD

**Issue by slawekjaranowski** [elastic/elasticsearch-java#775]
### Java API client version

8.13.0

### Java version

1.8

### Elasticsearch Version

8.11.3

### Problem description

In: `co.elastic.clients.elasticsearch.indices.PutIndexTemplateRequest` we have:

```
	@Nullable
	private final Integer priority;
```

but in: `co.elastic.clients.elasticsearch.indices.IndexTemplate` we have:

```
	@Nullable
	private final Long priority;
```

Looks like is the same field used by different endpoint, so should have the same type in API.

**Comment by l-trotta** [comment]
Hello, thanks for reporting this! I'll check which one is the correct one and make sure it's consistent everywhere.

**Comment by l-trotta** [comment]
[fixed](https://github.com/elastic/elasticsearch-java/commit/f91f275041b0d449a735ff58b8fc44b49912bc9b), will be part of the next minor version
