### ISSUE TITLE
TermsBucketBase: doc_count_error should be doc_count_error_upper_bound

### ISSUE THREAD

**Issue by stures** [elastic/elasticsearch-java#785]
### Java API client version

8.13

### Java version

21

### Elasticsearch Version

8.13

### Problem description

In the TermsBucketBase here:
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html#_per_bucket_document_count_error

The returned field is specified to `doc_count_error_upper_bound `

but the client expects: `doc_count_error `

https://github.com/elastic/elasticsearch-java/blob/c84fb7590f5bb700e653a1d2921de2fd01e0f2a3/java-client/src/main/java/co/elastic/clients/elasticsearch/_types/aggregations/TermsBucketBase.java#L110

This causes errors when using this request

**Comment by l-trotta** [comment]
Hello! Thank you for reporting this, I'm getting a different error so I'll have to investigate this a bit more, but something is definitely not working.
