### ISSUE TITLE
Assign a tokenizer to a field when creating an index. 8.6.0

### ISSUE THREAD

**Issue by billy723** [elastic/elasticsearch-java#788]
### Description

I have created a model class and I hope to use it to create an index. I am currently facing a problem. How can I specify a word breaker for certain fields in the index? And how to specify that certain fields are not segmented.

JDK version： 11

Maven Info：
        <dependency>
            <groupId>co.elastic.clients</groupId>
            <artifactId>elasticsearch-java</artifactId>
            <version>8.6.0</version>
        </dependency>

**Comment by l-trotta** [comment]
Hello! We use GitHub issues for verified bug reports, feature requests, and pull requests. This is a question, and we'd like to direct these kinds of things to the [Elastic Discuss Forum](https://discuss.elastic.co/tag/language-clients). If you can stop by there, we'd appreciate it. Thank you for your your understanding.
