### ISSUE TITLE
UpdateOperation don't support script

### ISSUE THREAD

**Issue by bachden** [elastic/elasticsearch-java#81]
in the old `RestHighLevelClient`, I can execute a bulk request with an update-using-script operation. It doesn't seem to work
 in this new client.

**Comment by swallez** [comment]
The API specification has been fixed in https://github.com/elastic/elasticsearch-specification/pull/1312

The next pass of code generation will fix the issue.

**Comment by swallez** [comment]
The API specification has been fixed in https://github.com/elastic/elasticsearch-specification/pull/1312

The next pass of code generation will fix the issue.
