### ISSUE TITLE
Link to Javadoc doesn't contain version

### ISSUE THREAD

**Issue by angles-n-daemons** [elastic/elasticsearch-java#83]
Not sure if this is intentional, but the PR to [add links to the Javadoc and Github repo](https://github.com/elastic/elasticsearch-java/commit/6bbde29110c2e2379a27dc462e5106684e238141) added a link to the javadoc that doesn't work. Not sure how link templating works, but it isn't properly formatting the links. Happy to open a PR if it makes sense that this should be fixed

**Comment by swallez** [comment]
Thanks for the heads up @angles-n-daemons. This (and other broken links) should be fixed in PR #92

**Comment by swallez** [comment]
Confirmed. The docs have been published and the links are correct: https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/current/java-client-javadoc.html

**Comment by angles-n-daemons** [comment]
Awesome, thanks for the quick fix!
