### ISSUE TITLE
AllocationRecord has no nodeRole method

### ISSUE THREAD

**Issue by mariuszpala** [elastic/elasticsearch-java#835]
### Java API client version

8.14.1

### Java version

21

### Elasticsearch Version

8.14.1

### Problem description

The AllocationRecord class has no nodeRole method although _cat/allocation return node.role, all other properties are available in the record except nodeRole

**Comment by l-trotta** [comment]
Hello, thanks for reporting this! The field seems to be missing from the [API specification](https://github.com/elastic/elasticsearch-specification) used to produce the Java code, once added there we'll regenerate the client to solve the issue.

**Comment by mariuszpala** [comment]
Thank you, in which version of the library this fix is available?

**Comment by l-trotta** [comment]
Not yet available! It will be either in the next 8.14.X (after 8.14.3) or 8.15
