### ISSUE TITLE
What is the alternative to RestHighLevelClient for Spring Boot 3.3.0 and Java 21?

### ISSUE THREAD

**Issue by hkathi-loyaltymethods** [elastic/elasticsearch-java#836]
### Description

Since the **RestHighLevelClient** is deprecated since the 7.16.0 of the ElasticSearch Version
https://github.com/elastic/elasticsearch/blob/78509f44d1e906f715b92abffdef1c467d4eaa2a/client/rest-high-level/src/main/java/org/elasticsearch/client/RestHighLevelClient.java#L253-L257

**Comment by swallez** [comment]
As written in the javadoc comment you linked to, _"The High Level Rest Client is deprecated in favor of the [Elasticsearch Java API Client](https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/current/introduction.html)"_ which is this repository. The documentation contains some instruction on [getting started on the migration](https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/current/migrate-hlrc.html).

I'm closing this, as this is a question and not an issue. If you have further questions, [please ask them in the Discuss forum](https://discuss.elastic.co/tag/language-clients). Thank you.
