### ISSUE TITLE
How to add documents in bulk operation?

### ISSUE THREAD

**Issue by kid1412621** [elastic/elasticsearch-java#84]
I only found a method for adding single doc: `co.elastic.clients.elasticsearch.core.BulkRequest.Builder::addDocument`

**Comment by yuhaowin** [comment]
```
        AppData appData = new AppData();
        appData.setIntValue(42);
        appData.setMsg("Some message");

        BulkResponse bulk = client.bulk(_0 -> _0
            .operations(_1 -> _1
                .create(_2 -> _2
                    .index("foo")
                    .id("abc")
                    .document(appData)
            ))
            .operations(_1 -> _1
                .create(_2 -> _2
                    .index("foo")
                    .id("def")
                    .document(appData)
            ))
        );
```

[this code in test](https://github.com/elastic/elasticsearch-java/blob/75feae536d2c9bce755236c979416fd9d0652803/java-client/src/test/java/co/elastic/clients/elasticsearch/end_to_end/RequestTest.java#L228)

**Comment by swallez** [comment]
7.15 was a beta version with some missing features. This is supported in 7.16.0, the first GA version.
