### ISSUE TITLE
MissingRequiredPropertyException for docsRemaining property which comes as null from elasticsearch

### ISSUE THREAD

**Issue by arsalaan997** [elastic/elasticsearch-java#842]
### Java API client version

8.13.4

### Java version

11

### Elasticsearch Version

8.10.2

### Problem description

There are conditions when totalDocs, docsRemaining & percentComplete are null in object of TransformProgress class. These fields should not be mandatory.

```[tasklist]
### Tasks
```

**Comment by l-trotta** [comment]
Hello, thanks for reporting this! Yes this looks correct, we'll also check the other fields in `TransformProgress` to make sure they're correct; then we'll fix it in the [API specification](https://github.com/elastic/elasticsearch-specification) and regenerate the java client to solve this issue.
