### ISSUE TITLE
Java/kotlin ElasticSearchAsyncClient several issues to check priorities

### ISSUE THREAD

**Issue by youngsam-byun** [elastic/elasticsearch-java#845]
### Description

Hi 
Thank you for your support
This is related to Java/Kotlin Client library

I am current using ElasticSearchAsyncClient , Kotlin 7.17.22 with Maven

Can you please answer my below questions ?
I want to know if you have any plan to support below mentioned features
1) If so, when would be the release ?
2) If not, Please indicate clearly

#1 and #2 are very important for production stability 
I hope you prioritize these 
Appreciate your answer

1. Feature/function accept retrial on failures  such as network connection failure or index update failures etc

https://github.com/elastic/elasticsearch-java/issues/356

2. Reactive API      
It would be great to use reactive API feature such as back pressure considering multiple clients with different capacities and network speed

https://github.com/elastic/elasticsearch-java/issues/542

3. TypeSafe builders with compatible with Kotlin DSL
Below link example improves usage and readability greatly    
   
https://github.com/elastic/elasticsearch-java/issues/117

4. TimeBuilder time unit accepts string in PointInTime
    There  must be better way to be type safe and elegant

https://github.com/elastic/elasticsearch-java/issues/90

Thank you

**Comment by l-trotta** [comment]
closing in favor of https://discuss.elastic.co/t/java-kotlin-elasticsearchasyncclient-several-issues-to-check-priorities/363123
