### ISSUE TITLE
significant terms aggregation missing regex include method

### ISSUE THREAD

**Issue by tatarco** [elastic/elasticsearch-java#85]
Hello,
by documentation of SignificantTermsAggregation should support regex aggregation
[Documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-significantterms-aggregation.html#_filtering_values_2)

The object  new TermsAggregation.Builder() is missing the include method that supports it
it only has
public final Builder include(String value) when for exclude the currect implemtation exists (TermsExclude exclude)

it's expected that the object will have 
private final TermsInclude include;
as in TermsAggregation.Builder

not having it causes the wrong behavior and elastic to not use regex for filtering

**Comment by swallez** [comment]
This is a problem in the API specification used to produce the Java code: an issue has been opened at https://github.com/elastic/elasticsearch-specification/issues/1553

Once the API spec has been fixed, this issue will be resolved in the next minor release.

**Comment by swallez** [comment]
Java code has been updated, this is included in 7.17.3 and will be in the upcoming 8.2.0.
