### ISSUE TITLE
There is a conflict between the package types of the two versions.

### ISSUE THREAD

**Issue by aiYunS-love** [elastic/elasticsearch-java#859]
### Java API client version

5.3.2

### Java version

21.0.4

### Elasticsearch Version

7.17.23

### Problem description

<img width="838" alt="65A64D319DE99AB65FD6B36511BD7636" src="https://github.com/user-attachments/assets/ea8e65d5-6a22-45b0-ae1b-a735561a5531">
<img width="660" alt="987FB4D647E725DF226AAA2DBD9B7A3A" src="https://github.com/user-attachments/assets/36ed9282-1bd1-479b-95e7-cb4ff91d97bc">

**Comment by l-trotta** [comment]
Hello! The project you're using is [spring-data-elasticsearch](https://github.com/spring-projects/spring-data-elasticsearch), which is built using the elasticsearch java client (this repo) and is not maintained by us. It could be our fault that we accidentally introduced a breaking change in version 7.17.23, but in any case if the spring project isn't updated we cannot do anything about it.
