### ISSUE TITLE
Why are the fields 'ruleType', 'nametype', and 'languageSet' mandatory for the 'phonetictokenfilter'?

### ISSUE THREAD

**Issue by powfyy** [elastic/elasticsearch-java#874]
### Java API client version

8.13.4

### Java version

17

### Elasticsearch Version

8.12.2

### Problem description

Why are the fields 'ruleType', 'nametype', and 'languageSet' mandatory for the 'PhoneticTokenFilter'? I'm using the 'double metaphone encoder', so these parameters are not specified in the index schema. When I try to execute the query `elasticsearchClient.indices().getSettings(GetIndicesSettingsRequest.of(ginsr -> ginsr
        .index(oldIndex))).result().get(oldIndex).settings().index().numberOfReplicas();` I get an error "Failed to decode response. co.elastic.clients.util.MissingRequiredPropertyException: Missing required property 'PhoneticTokenFilter.<languageset/ruleType/nameType>'"

**Comment by l-trotta** [comment]
Because it's a bug, thanks for reporting it! We'll fix it soon.

**Comment by l-trotta** [comment]
Just noticed that this was already fixed with this [PR](https://github.com/elastic/elasticsearch-specification/pull/2813) in the API spec, used to generate the clients. Simply update to the more recent version to solve the issue.
