### ISSUE TITLE
`java-client/src/main/java/co/elastic/clients/elasticsearch/indices/update_aliases/Action.java` The Builder of Action of updateAliases should use [return self()] instead of [return this] and change the return type to [Builder]

### ISSUE THREAD

**Issue by Jiuyoung** [elastic/elasticsearch-java#884]
### Java API client version

8.15.1

### Java version

11

### Elasticsearch Version

8.15.0

### Problem description

The following is the relevant code, which is causing the inability to achieve chaining as expected.

[https://github.com/elastic/elasticsearch-java/blob/7c46ddd904f31cab870ad5804003af29408ffe6d/java-client/src/main/java/co/elastic/clients/elasticsearch/indices/update_aliases/Action.java#L198-L230](https://github.com/elastic/elasticsearch-java/blob/7c46ddd904f31cab870ad5804003af29408ffe6d/java-client/src/main/java/co/elastic/clients/elasticsearch/indices/update_aliases/Action.java#L198-L230)

**Comment by l-trotta** [comment]
Hello! I'm a bit confused, since this is the same pattern used in all the classes of the client. Could you show me which kind of chaining are you trying to achieve?

**Comment by Jiuyoung** [comment]
@l-trotta 

Thanks for your comment. The following code describes this situation.

```java
public static void main(String[] args) throws IOException {
    // DESC: I would like to rewrite the following code to use chaining.
    es.indices().updateAliases(
            request -> request.actions(
                    actionsBuilder -> {
                        // DESC: these code used to build actions list
                        actionsBuilder.add(add -> add.alias("alias1").index("index1"));
                        actionsBuilder.add(add -> add.alias("alias1").index("index2"));
                        return actionsBuilder;
                    }
            )
    );
    // DESC: I am trying to write the following code
    es.indices().updateAliases(
            request -> request.actions(
                    actionsBuilder -> actionsBuilder
                            .add(add -> add.alias("alias1").index("index1"))
                            // ERROR: This will not work as expected with error [Cannot resolve method 'add' in 'ObjectBuilder']
                            .add(add -> add.alias("alias1").index("index2"))
            )
    );
}

```

This picture show code in IDEA.
![Image](https://github.com/user-attachments/assets/7461ace6-affc-4648-94dd-5740fe3541bd)

**Comment by l-trotta** [comment]
Got it! So for builders that allow multiple values we have 3 types of constructors:
![Image](https://github.com/user-attachments/assets/db7892ef-708f-44a6-9709-39c13c2dac4c)
The last one just works for a single value, so to add multiple value you can either use a list:
```java
es.indices().updateAliases(
    u -> u.actions(List.of(Action.of(a -> a.add(add -> add.alias("alias1").index("index1"))),
        Action.of(a -> a.add(add -> add.alias("alias1").index("index1"))))
    )
);
```

or comma separated values:
```java
es.indices().updateAliases(
    u -> u.actions(Action.of(a -> a.add(add -> add.alias("alias1").index("index1"))),
        Action.of(a -> a.add(add -> add.alias("alias1").index("index1")))
    )
);
```
We chose this approach to keep the syntax of the request similar to the original json one, which accepts a list of values or a single value.

**Comment by Jiuyoung** [comment]
^_^ Very nice! Thank you! I will close this issue.
