### ISSUE TITLE
How to get aggregation result in searchTemplate [7.16.2]

### ISSUE THREAD

**Issue by forachange** [elastic/elasticsearch-java#89]
7.16，Elasticsearch Java API Client

`SearchTemplateResponse<Object> response =  ElasticSearchClient.searchTemplate(request, Object.class);`

The `response` just have the `hits` property to get the search result, but how to get aggregation result ?

**Comment by swallez** [comment]
Thanks for reporting this issue. The upstream API specification has been fixed in https://github.com/elastic/elasticsearch-specification/pull/1335

The next pass of code generation will fix the issue.
