### ISSUE TITLE
How to Improve Deserialization of TasksRecord in Elasticsearch Java Client

### ISSUE THREAD

**Issue by Rodma1** [elastic/elasticsearch-java#896]
---
elsaticsearch: 8.11.4
elasticsearch-java: 8.11.4
java8

### Issue: How to Improve Deserialization of `TasksRecord` in Elasticsearch Java Client

I am querying task records from Elasticsearch using the Java client like this:

```java
List<TasksRecord> tasksRecords = client.cat().tasks().valueBody();
```

Currently, I am attempting to deserialize these `TasksRecord` objects into a `Map` using the following approach:

```java
tasksRecords.forEach(item -> {
    String className = item.getClass().getSimpleName() + ": ";
    String replace = item.toString().replace(className, "");
    hashMaps.add(FastJsonUtils.toObject(replace));
});
```

In this code:
1. I extract the string representation of each `TasksRecord`.
2. Remove the class name prefix.
3. Use `FastJsonUtils.toObject()` to deserialize the modified string into a `Map`.

I believe this solution is not ideal because it relies heavily on string manipulation, which can be error-prone and inefficient.

My main question is: **How can I improve the deserialization process?**
- Is there a better way to directly deserialize `TasksRecord` into a `Map` or another structure, leveraging existing Elasticsearch client functionality?
- How can I avoid manual string replacement and use a more efficient or standardized approach?

I would greatly appreciate any advice or best practices for optimizing this code.

---

**Comment by l-trotta** [comment]
Hello! We have existing utilities to directly convert Elasticsearch client types to Maps, but we do have some other utilities that we can leverage to avoid string manipulation. Here's what I would to to convert a list of `TaskRecord`s into a list of maps:

```java
JacksonJsonpMapper jsonpMapper = new JacksonJsonpMapper(); // using Jackson mapper because it's the one we recommend

ElasticsearchTransport transport = new RestClientTransport(restClient, jsonpMapper); // restClient required of course

ElasticsearchClient esClient = new ElasticsearchClient(transport); //instance of the client

List<TasksRecord> taskList = esClient.cat().tasks().valueBody(); // getting the task records like you did

JsonProvider provider = JsonpUtils.provider(); // this is available from the client utilities, no need to import anything else

List<HashMap> maps = taskList.stream().map(task -> {
    StringWriter sw = new StringWriter(); // where the serialized json string will be written
    JsonGenerator generator = provider.createGenerator(sw); 

    task.serialize(generator,jsonpMapper); // this just outputs the json, no class name or other characters

    generator.close(); // flushing the buffer into the string writer

    return jsonpMapper.deserialize(jsonpMapper.jsonProvider().createParser(new StringReader(sw.toString())),HashMap.class); // deserializing the json string to a map
}).toList();
```

The result will be a `List<Map<String,String>>`. Hope this helps!

**Comment by Rodma1** [comment]
---


**Description:**
I am trying to deserialize an `IndexTemplateItem` retrieved from Elasticsearch using the `JacksonJsonpMapper`, but I encounter the following error:

```
IllegalArgumentException: Jackson's ObjectMapper can only be used with the JacksonJsonpProvider
```

**Code Snippet:**
```java
IndexTemplateItem indexTemplateItem = client.indices().getIndexTemplate(t -> t.name(indexTemplate)).indexTemplates().get(0);
JacksonJsonpMapper jsonpMapper = new JacksonJsonpMapper(); // Using Jackson mapper as recommended
StringWriter sw = new StringWriter(); // Where the serialized JSON string will be written
JsonProvider provider = JsonpUtils.provider(); // Available from the client utilities

JsonGenerator generator = provider.createGenerator(sw);
indexTemplateItem.serialize(generator, jsonpMapper); // Outputs the JSON

generator.close(); // Flushes the buffer into the string writer

return jsonpMapper.deserialize(jsonpMapper.jsonProvider().createParser(new StringReader(sw.toString())), HashMap.class); // Deserializing the JSON string to a map
```

**Expected Behavior:**
I expect to serialize the `IndexTemplateItem` into a JSON string and then deserialize it into a `HashMap`.

**Actual Behavior:**
The code throws an `IllegalArgumentException` indicating that the `ObjectMapper` can only be used with the `JacksonJsonpProvider`.

**Additional Context:**
I have ensured that I am using the `JacksonJsonpMapper`, but the issue persists. 

---

**Comment by l-trotta** [comment]
Just replace 
```java
JsonProvider provider = JsonpUtils.provider();
```
 with 

```java
JsonProvider provider = jsonpMapper.jsonProvider();
```
