### ISSUE TITLE
How to print search query?

### ISSUE THREAD

**Issue by X-rapido** [elastic/elasticsearch-java#97]
hi, 

before used "elasticsearch-rest-high-level-client.jar",  in SearchSourceBuilder.java can print  the DSL query
```
SearchSourceBuilder searchSourceBuilder = new SearchSourceBuilder();
searchSourceBuilder.query(boolQuery);
...
logger.info("=====DSL====="+searchSourceBuilder.toString());
```

I‘m trying "elasticsearch-java.jar" ,  please tell me how to print the  DSL SearchRequest query?

```
SearchRequest searchRequest = SearchRequest.of(s -> s
                .index(indexName)
                .query(q -> q
                        .term(t -> t
                                .field("goodsId")
                                .value(v -> v.stringValue("1"))
                        )));

```
i',m debugging. no found the record。 please help！

**Comment by zoom2madan** [comment]
You can try the approach suggested in this stackoverflow post
https://stackoverflow.com/questions/60849887/log-json-queries-built-through-elasticsearch-high-level-java-client-for-debuggin

I have tried this approach with below version of ES client, and it works.
<dependency>
	<groupId>co.elastic.clients</groupId>
	<artifactId>elasticsearch-java</artifactId>
	<version>7.16.1</version>
</dependency>

**Comment by X-rapido** [comment]
Part of my code
```xml
<dependency>
    <groupId>co.elastic.clients</groupId>
    <artifactId>elasticsearch-java</artifactId>
    <version>7.16.2</version>
</dependency>
```

search test
```java
import co.elastic.clients.elasticsearch.ElasticsearchClient;
import co.elastic.clients.elasticsearch.core.SearchRequest;
import co.elastic.clients.elasticsearch.core.SearchResponse;
import co.elastic.clients.elasticsearch.core.search.Hit;
import com.tingfeng.vo.IndexProductVo;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
public class EsTest {

    @Autowired
    private ElasticsearchClient client;

    @Test
    public void search() throws Exception {
        SearchRequest searchRequest = SearchRequest.of(s -> s
                .index("demo")
                .query(q -> q
                        .term(t -> t
                                .field("goodsId")
                                .value(v -> v.stringValue("1"))
                        )));

        System.out.println("--- DSL query---：");    // How do I print DSL here？？

        SearchResponse<IndexProductVo> search = client.search(searchRequest, IndexProductVo.class);
        for (Hit<IndexProductVo> hit : search.hits().hits()) {
            System.out.println(hit.source()); // Have the results
        }
    }
}
```

"elasticsearch-java.jar"  How do I print DSL here?

**Comment by Dyqer** [comment]
@X-rapido 
```
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        JsonGenerator generator = transport.jsonpMapper().jsonProvider().createGenerator(baos);
        searchRequest.serialize(generator, transport.jsonpMapper());
        generator.close();
        System.out.println(baos);
```

**Comment by X-rapido** [comment]
> @X-rapido
> 
> ```
>         ByteArrayOutputStream baos = new ByteArrayOutputStream();
>         JsonGenerator generator = transport.jsonpMapper().jsonProvider().createGenerator(baos);
>         searchRequest.serialize(generator, transport.jsonpMapper());
>         generator.close();
>         System.out.println(baos);
> ```

Thank's

**Comment by hezhiliang** [comment]
> hi,
> 
> before used "elasticsearch-rest-high-level-client.jar", in SearchSourceBuilder.java can print the DSL query
> 
> ```
> SearchSourceBuilder searchSourceBuilder = new SearchSourceBuilder();
> searchSourceBuilder.query(boolQuery);
> ...
> logger.info("=====DSL====="+searchSourceBuilder.toString());
> ```
> 
> I‘m trying "elasticsearch-java.jar" , please tell me how to print the DSL SearchRequest query?
> 
> ```
> SearchRequest searchRequest = SearchRequest.of(s -> s
>                 .index(indexName)
>                 .query(q -> q
>                         .term(t -> t
>                                 .field("goodsId")
>                                 .value(v -> v.stringValue("1"))
>                         )));
> ```
> 
> i',m debugging. no found the record。 please help！

The toString() method is overwritten in the "elasticsearch-rest-high-level-client" version, but not in the "elasticsearch-java (8.2.2)" version. As a result, it is not easy to print DSL statements in the development test.  I see that this issue is now being optimized and look forward to a new release that addresses this issue.

**Comment by vincentchen007** [comment]
hello @swallez 
I also had this issue on "elasticsearch-java (8.1)" version.
could you please help? thank you
